import {useMemo,useState} from 'react';
import {Search,ChevronRight} from 'lucide-react';
import {ChapterNoteSections} from '../components/chapter-note-sections';
import {bookThoughtLocation,chapterNotes,notebookBooks,type BookNote} from '../lib/book-notebook';
import {crossNumber,numberOf,type Notebook} from '../lib/notebook';

export function MobileBookNotes({data,onQuestion,onBook}:{data:Notebook;onQuestion:(id:string)=>void;onBook:(id:string,location?:string,readingId?:string,thoughtId?:string,chapter?:string)=>void}){
 const [query,setQuery]=useState(''),[kind,setKind]=useState('all');
 const books=useMemo(()=>notebookBooks(data),[data]);
 const label=(id:string)=>{const question=data.notes.find(note=>note.id===id);if(question)return `${question.parent?numberOf(question,data.notes,data.crossThoughts):'核心问题'} · ${question.title}`;const cross=data.crossThoughts.find(item=>item.id===id);return cross?`${crossNumber(cross)} · ${cross.title||cross.text}`:'已移除的问题';};
 const needle=query.trim().toLocaleLowerCase();
 const matches=(entry:BookNote,title:string)=> (kind==='all'||entry.kind===kind)&&(!needle||[title,entry.note.chapter,entry.note.quote,entry.kind==='process'?entry.note.interpretation:entry.note.text,entry.note.locator,...entry.note.thoughts.map(t=>t.text)].filter(Boolean).join('\n').toLocaleLowerCase().includes(needle));
 const visible=books.map(book=>({...book,entries:book.entries.filter(entry=>matches(entry,book.title))})).filter(book=>book.entries.length);
 return <><div className="mobile-search"><Search size={18}/><input aria-label="搜索书籍笔记" value={query} placeholder="找书名、章节或想法" onChange={event=>setQuery(event.target.value)}/></div><div className="mobile-note-filters">{[['all','全部'],['process','过程笔记'],['reading','读书笔记']].map(([value,title])=><button key={value} aria-pressed={kind===value} onClick={()=>setKind(value)}>{title}</button>)}</div><section className="mobile-notes" aria-label="分书分章节笔记">{visible.map(book=><details className="mobile-note-book" key={book.key} open={needle?true:undefined}><summary><ChevronRight size={17}/><div><strong>{book.title}</strong><small>{book.author||(!book.book?'原文件未在书库中':'')}{book.author?' · ':''}{book.entries.length} 条笔记</small></div></summary><ChapterNoteSections groups={chapterNotes(book.entries,book.book).filter(group=>!needle||group.entries.length>0)} expandKey={needle} onAdd={book.book?(chapter)=>onBook(book.book!.id,undefined,undefined,undefined,chapter):undefined} renderNote={item=>{const note=item.note;return <article key={note.id}><header><span>{item.kind==='process'?'过程笔记':'读书笔记'} · {item.kind==='reading'?bookThoughtLocation(item.note):note.locator}</span><time>{new Date(note.at).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}</time></header>{note.quote&&<blockquote>{note.quote}</blockquote>}<p>{item.kind==='process'?item.note.interpretation:item.note.text}</p>{!!note.questionIds.length&&<div className="book-thought-links">{note.questionIds.map(id=><button key={id} onClick={()=>onQuestion(id)}>{label(id)}</button>)}</div>}{note.thoughts.map(thought=><aside key={thought.id}><small>{new Date(thought.at).toLocaleString('zh-CN')} · {thought.origin}</small><p>{thought.text}</p>{thought.reason&&<em>修改原因：{thought.reason}</em>}</aside>)}{book.book&&<footer><button onClick={()=>onBook(book.book!.id,note.sourceLocation,item.kind==='process'?note.id:undefined,item.kind==='reading'&&!note.sourceLocation?note.id:undefined)}>{note.sourceLocation?'回到原文':'打开本书笔记'}</button></footer>}</article>;}}/></details>)}{!visible.length&&<p className="mobile-empty">{needle||kind!=='all'?'没有找到匹配的笔记。':'阅读时留下的注解与思考会保留在这里。'}</p>}</section></>;
}
