'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {deletionPlan} from '@/lib/deletion';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription} from '@/components/ui/alert-dialog';
import {CrossBlockPicker} from '@/components/cross-block-picker';
import {ReadingNotes} from '@/components/reading-notes';
import {Manuscripts} from '@/components/manuscripts';
import {LibraryReader} from '@/components/library-reader';
import {GlobalSearch} from '@/components/global-search';
import {CloudLibrary} from '@/components/cloud-library';
import {readDraft,writeDraft} from '@/lib/draft-storage';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {Input} from '@/components/ui/input';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Trash2,Plus,Minus,Maximize,Link2,ArrowUpRight,Check,Loader2,Lightbulb,GitBranch,MessageSquare,Archive,CornerDownRight,Unlink,Network,History,FileText,Share2,Library,Search} from 'lucide-react';
import {type Notebook,type Thought,type ThoughtReply,type Card,type Note,type CrossThought,normalize,numberOf,crossNumber,crossSignature,itemText,suggestions,ROOT} from '@/lib/notebook';
import {readOnlyHtml} from '@/lib/read-only-export';
type FormKind={kind:'question'|'answer'|'link';from:string}|null;
type Draft={text:string;origin:string;reason:string;changed:boolean};
type HomeDraft={capture:string;captureOrigin:string;captureSource:string;drafts:Record<string,Draft>;form:FormKind;title:string;body:string;target:string;relation:string;replyingThoughtId:string|null;replyText:string};
type HistoryEntry={id:string;kind:string;at:string;ownerId:string;owner:string;text:string;reason?:string;manuscriptId?:string};
const blankDraft:Draft={text:'',origin:'自己的思考',reason:'',changed:false};
const origins=['自己的思考','材料触发的想法','引用他人观点'];
function when(at:string){return at?new Date(at).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'最初记录';}
function short(text:string,length=50){return text.length>length?text.slice(0,length)+'…':text;}
export default function Home(){
 const [data,setData]=useState<Notebook>({notes:[],cards:[],readingNotes:[],crossThoughts:[],thoughtReplies:[],manuscripts:[],libraryBooks:[],libraryHighlights:[],ocrCache:[],bookThoughts:[],links:[],dismissedSuggestions:[]}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[sharing,setSharing]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [storage,setStorage]=useState<'local'|'nutstore'|'web'>('web');
 const [deleting,setDeleting]=useState<string|null>(null),[deleteStep,setDeleteStep]=useState(1),[deleteText,setDeleteText]=useState('');
 const [boxOpen,setBoxOpen]=useState(false),[historyOpen,setHistoryOpen]=useState(false),[searchOpen,setSearchOpen]=useState(false),[cloudOpen,setCloudOpen]=useState(false),[manuscriptsOpen,setManuscriptsOpen]=useState(false),[manuscriptInitialId,setManuscriptInitialId]=useState<string|null>(null),[readingInitialId,setReadingInitialId]=useState<string|null>(null),[readingInitialThoughtId,setReadingInitialThoughtId]=useState<string|null>(null),[standaloneReadingId,setStandaloneReadingId]=useState<string|null>(null),[libraryOpen,setLibraryOpen]=useState(false),[libraryInitialId,setLibraryInitialId]=useState<string|null>(null),[libraryInitialLocation,setLibraryInitialLocation]=useState<string|null>(null),[libraryInitialBookThoughtId,setLibraryInitialBookThoughtId]=useState<string|null>(null),[libraryInitialDetachedThoughtId,setLibraryInitialDetachedThoughtId]=useState<string|null>(null);
 const [crossPicker,setCrossPicker]=useState(false),[editingCross,setEditingCross]=useState<string|null>(null);
 const [replyingThoughtId,setReplyingThoughtId]=useState<string|null>(null),[focusedThoughtId,setFocusedThoughtId]=useState<string|null>(null),[replyText,setReplyText]=useState('');
 const [capture,setCapture]=useState(''),[captureOrigin,setCaptureOrigin]=useState(origins[0]),[captureSource,setCaptureSource]=useState(''),[selected,setSelected]=useState<string|null>(null),[drafts,setDrafts]=useState<Record<string,Draft>>({}),[form,setForm]=useState<FormKind>(null),[title,setTitle]=useState(''),[body,setBody]=useState(''),[target,setTarget]=useState(''),[relation,setRelation]=useState('相关');
 const [homeDraftReady,setHomeDraftReady]=useState(false);
 const [viewport,setViewport]=useState({width:900,height:650}),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:150,y:200});const graphRef=useRef<HTMLDivElement>(null);const drag=useRef<{x:number;y:number;px:number;py:number}|null>(null);const captureRef=useRef<HTMLTextAreaElement>(null);
 const versionRef=useRef(0),savingRef=useRef(false);
 const draftWriteQueueRef=useRef<Promise<void>>(Promise.resolve());
 const card=data.cards.find(c=>c.id===selected),note=data.notes.find(n=>n.id===selected),cross=data.crossThoughts.find(c=>c.id===selected),draft=selected?(drafts[selected]||blankDraft):blankDraft;
 const noteNumber=(n:Note)=>numberOf(n,data.notes,data.crossThoughts);
 const crossCode=(c:CrossThought)=>`${crossNumber(c)}〔${crossSignature(c,data)}〕`;
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/notebook');const j=await r.json() as {data:Notebook;version:number;storage?:'local'|'nutstore';error:string};if(!r.ok)throw Error(j.error);setData(normalize(j.data));versionRef.current=j.version;setStorage(j.storage==='nutstore'?'nutstore':j.storage==='local'?'local':'web');}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 useEffect(()=>{const openCloud=()=>setCloudOpen(true);window.addEventListener('wenjian-open-cloud',openCloud);return()=>window.removeEventListener('wenjian-open-cloud',openCloud);},[]);
 useEffect(()=>{let cancelled=false;readDraft<HomeDraft|null>('home',null).then(saved=>{
  if(cancelled)return;
  if(saved&&typeof saved==='object'){
   setCapture(current=>current||saved.capture||'');setCaptureOrigin(saved.captureOrigin||origins[0]);setCaptureSource(current=>current||saved.captureSource||'');
   if(saved.drafts&&typeof saved.drafts==='object')setDrafts(current=>({...saved.drafts,...current}));
   if(saved.form){setForm(current=>current||saved.form);setTitle(current=>current||saved.title||'');setBody(current=>current||saved.body||'');setTarget(current=>current||saved.target||'');setRelation(saved.relation||'相关');}
   if(saved.replyingThoughtId&&saved.replyText){setReplyingThoughtId(saved.replyingThoughtId);setReplyText(current=>current||saved.replyText);}
  }
  setHomeDraftReady(true);
 }).catch(e=>{if(!cancelled)setError(`草稿读取失败：${(e as Error).message}`);});return()=>{cancelled=true;};},[]);
 useEffect(()=>{if(!homeDraftReady)return;const snapshot:HomeDraft={capture,captureOrigin,captureSource,drafts,form,title,body,target,relation,replyingThoughtId,replyText};const timer=window.setTimeout(()=>{draftWriteQueueRef.current=draftWriteQueueRef.current.catch(()=>{}).then(()=>writeDraft('home',snapshot));draftWriteQueueRef.current.catch(e=>setError(`草稿未能自动保存：${(e as Error).message}`));},300);return()=>window.clearTimeout(timer);},[homeDraftReady,capture,captureOrigin,captureSource,drafts,form,title,body,target,relation,replyingThoughtId,replyText]);
 useEffect(()=>{if(!graphRef.current)return;const ro=new ResizeObserver(([e])=>setViewport({width:e.contentRect.width,height:e.contentRect.height}));ro.observe(graphRef.current);return()=>ro.disconnect();},[]);
 useEffect(()=>{if(!message)return;const t=setTimeout(()=>setMessage(''),4500);return()=>clearTimeout(t);},[message]);
 useEffect(()=>{if(!capture&&!Object.values(drafts).some(d=>d.text)&&!form)return;const f=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f);},[capture,drafts,form]);
 async function save(next:Notebook,feedback:string){if(savingRef.current){if(feedback)setError('上一项内容仍在保存，请稍候再试。');return false;}savingRef.current=true;setSaving(true);setError('');try{const r=await fetch('/api/notebook',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({data:next,version:versionRef.current})});const j=await r.json() as {version:number;error:string};if(!r.ok)throw Error(j.error);setData(next);versionRef.current=j.version;if(feedback)setMessage(feedback);return true;}catch(e){setError((e as Error).message);return false;}finally{savingRef.current=false;setSaving(false);}}
 async function deleteLibraryBook(bookId:string,title:string){if(savingRef.current)return false;savingRef.current=true;setSaving(true);setError('');try{const r=await fetch('/api/library/delete',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:bookId,title,version:versionRef.current,confirmed:true,confirmation:'删除'})});const j=await r.json() as {data:Notebook;version:number;error?:string};if(!r.ok)throw Error(j.error||'书籍没有删除。');setData(normalize(j.data));versionRef.current=j.version;if(libraryInitialId===bookId){setLibraryInitialId(null);setLibraryInitialLocation(null);}setMessage('书籍已删除，已有阅读笔记仍然保留');return true;}catch(e){setError((e as Error).message);return false;}finally{savingRef.current=false;setSaving(false);}}
 async function shareReadOnly(){if(sharing)return;setSharing(true);setError('');try{const r=await fetch('/api/share',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({html:readOnlyHtml(data),filename:`问间-只读副本-${new Date().toISOString().slice(0,10)}.html`})});const j=await r.json() as {saved:boolean;error?:string};if(!r.ok)throw Error(j.error||'只读副本没有生成。');if(j.saved)setMessage('只读副本已保存，可以发送给别人');}catch(e){setError((e as Error).message);}finally{setSharing(false);}}
 async function captureCard(e:React.FormEvent){e.preventDefault();if(!capture.trim())return;const c:Card={id:crypto.randomUUID(),text:capture.trim(),origin:captureOrigin,source:captureSource,at:new Date().toISOString(),thoughts:[]};if(await save({...data,cards:[...data.cards,c]},'已保存')){setCapture('');setCaptureSource('');setCaptureOrigin(origins[0]);}}
 function changeDraft(p:Partial<Draft>){if(selected)setDrafts(d=>({...d,[selected]:{...(d[selected]||blankDraft),...p}}));}
 async function addThought(e:React.FormEvent){e.preventDefault();if(!selected||!draft.text.trim())return;if(draft.changed&&!draft.reason.trim()){setError('请记下为什么改变了判断。');return;}const thought:Thought={id:crypto.randomUUID(),text:draft.text.trim(),origin:draft.origin,reason:draft.changed?draft.reason.trim():'',at:new Date().toISOString()};const next={...data,cards:data.cards.map(c=>c.id===selected?{...c,thoughts:[...c.thoughts,thought]}:c),notes:data.notes.map(n=>n.id===selected?{...n,thoughts:[...(n.thoughts||[]),thought]}:n),crossThoughts:data.crossThoughts.map(c=>c.id===selected?{...c,thoughts:[...c.thoughts,thought]}:c)};if(await save(next,'已保存'))setDrafts(d=>({...d,[selected]:{...blankDraft}}));}
 async function saveThoughtReply(e:React.FormEvent){e.preventDefault();if(!replyingThoughtId||!replyText.trim()||data.thoughtReplies.some(r=>r.thoughtId===replyingThoughtId))return;const reply:ThoughtReply={id:crypto.randomUUID(),thoughtId:replyingThoughtId,text:replyText.trim(),at:new Date().toISOString()};if(await save({...data,thoughtReplies:[...data.thoughtReplies,reply]},'回答已保存')){setReplyingThoughtId(null);setReplyText('');}}
 function startCrossMode(){setEditingCross(null);setSelected(null);setCrossPicker(true);setError('');}
 function editCrossLinks(){if(!cross)return;setEditingCross(cross.id);setSelected(null);setCrossPicker(true);setError('');}
 function closeCrossPicker(){setCrossPicker(false);if(editingCross)setSelected(editingCross);setEditingCross(null);}
 async function saveCrossBlock(title:string,anchorIds:string[]){
  if(anchorIds.length<2)return;
  const existing=data.crossThoughts.find(c=>c.id===editingCross);
  const changed=existing&&JSON.stringify(existing.anchorIds)!==JSON.stringify(anchorIds);
  const entry:CrossThought=existing?{...existing,anchorIds,anchorRevisions:changed?[...existing.anchorRevisions,{from:existing.anchorIds,to:anchorIds,fromLabel:crossSignature(existing,data),toLabel:crossSignature({...existing,anchorIds},data),at:new Date().toISOString(),reason:'手动调整关联板块'}]:existing.anchorRevisions}:{id:crypto.randomUUID(),order:Math.max(0,...data.crossThoughts.map(c=>c.order))+1,title,anchorIds,anchorRevisions:[],text:'',origin:origins[0],source:'',at:new Date().toISOString(),thoughts:[]};
  const crossThoughts=existing?data.crossThoughts.map(c=>c.id===entry.id?entry:c):[...data.crossThoughts,entry];
  if(await save({...data,crossThoughts},existing?'关联已更新':'交叉板块已创建')){setCrossPicker(false);setEditingCross(null);setSelected(entry.id);}
 }
 function openForm(kind:'question'|'answer'|'link',from:string){setForm({kind,from});setTitle('');setBody('');setRelation('相关');setTarget(data.notes.find(n=>n.id!==from)?.id||data.crossThoughts.find(c=>c.id!==from)?.id||data.cards.find(c=>c.id!==from)?.id||'');setSelected(null);setError('');}
 async function submitForm(e:React.FormEvent){e.preventDefault();if(!form)return;const next={...data,notes:[...data.notes],links:[...data.links]};let id=form.from;if(form.kind==='link'){if(!target||target===form.from)return;if(data.links.some(l=>l.from===form.from&&l.to===target&&l.type===relation)){setError('这条联系已经存在。');return;}next.links.push({id:crypto.randomUUID(),from:form.from,to:target,type:relation});}
 else{const siblings=data.notes.filter(n=>n.kind===form.kind&&n.parent===form.from);const order=Math.max(0,...siblings.map(n=>n.order))+1;id=crypto.randomUUID();next.notes.push({id,kind:form.kind,parent:form.from,order,title:title.trim(),body,origin:'自己的思考',source:'',revisions:[],thoughts:[]});}
 if(await save(next,form.kind==='link'?'已连接':'已加入关系图。')){setForm(null);setSelected(id);}}
 async function accept(from:string,to:string){if(await save({...data,links:[...data.links,{id:crypto.randomUUID(),from,to,type:'相关'}]},'已连接'))setSelected(from);}
 const plan=deleting?deletionPlan(data,deleting):null;
 function beginDelete(id:string){setDeleting(id);setDeleteStep(1);setDeleteText('');setError('');setSelected(null);}
 function cancelDelete(){if(saving)return;setSelected(deleting);setDeleting(null);setDeleteStep(1);setDeleteText('');setError('');}
 async function deleteQuestion(){if(!plan||deleteStep!==2||deleteText!=='删除'||savingRef.current)return;savingRef.current=true;setSaving(true);setError('');try{const r=await fetch('/api/notebook',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:plan.target.id,title:plan.target.title,version:versionRef.current,confirmed:true,confirmation:deleteText})});const j=await r.json() as {data:Notebook;version:number;error:string};if(!r.ok)throw Error(j.error);setData(normalize(j.data));versionRef.current=j.version;setDrafts(d=>Object.fromEntries(Object.entries(d).filter(([id])=>!plan.ids.has(id))));setDeleting(null);setSelected(null);setDeleteText('');setMessage('子问题已删除');}catch(e){setError((e as Error).message);}finally{savingRef.current=false;setSaving(false);}}
 const shownCards=data.cards.filter(c=>data.links.some(l=>l.from===c.id||l.to===c.id));
 const ordinaryThoughts=[...data.notes.flatMap(n=>(n.thoughts||[]).map(t=>({...t,ownerId:n.id,ownerLabel:n.id===ROOT?'核心问题':noteNumber(n)}))),...data.cards.flatMap(c=>c.thoughts.map(t=>({...t,ownerId:c.id,ownerLabel:'卡片'})))];
 const thoughtContexts=[
  ...data.notes.flatMap(n=>(n.thoughts||[]).map(t=>({thought:t,ownerId:n.id,owner:n.id===ROOT?'核心问题':`${noteNumber(n)} · ${n.title}`}))),
  ...data.cards.flatMap(c=>c.thoughts.map(t=>({thought:t,ownerId:c.id,owner:`卡片 · ${short(c.text,34)}`}))),
  ...data.crossThoughts.flatMap(c=>c.thoughts.map(t=>({thought:t,ownerId:c.id,owner:`${crossCode(c)} · ${c.title||short(c.text,34)}`}))),
	  ...data.readingNotes.flatMap(r=>r.thoughts.map(t=>({thought:t,ownerId:r.questionIds[0]||ROOT,owner:`阅读笔记 · ${r.book}${r.chapter?' / '+r.chapter:''}`}))),
	  ...data.bookThoughts.flatMap(entry=>entry.thoughts.map(t=>({thought:t,ownerId:entry.questionIds[0]||ROOT,owner:`本书思考 · ${entry.bookTitle}${entry.locator?' / '+entry.locator:''}`})))
 ];
 const historyEntries:HistoryEntry[]=[
  ...thoughtContexts.map(({thought,ownerId,owner})=>({id:`thought:${thought.id}`,kind:thought.reason?'改变判断':'追加思考',at:thought.at,ownerId,owner,text:thought.text,reason:thought.reason||undefined})),
  ...data.thoughtReplies.map(reply=>{const context=thoughtContexts.find(item=>item.thought.id===reply.thoughtId);return {id:`reply:${reply.id}`,kind:'思考回答',at:reply.at,ownerId:context?.ownerId||ROOT,owner:context?.owner||'原思考',text:reply.text};}),
  ...data.notes.flatMap(n=>n.revisions.map((revision,index)=>({id:`revision:${n.id}:${index}`,kind:'修订记录',at:revision.at,ownerId:n.id,owner:n.id===ROOT?'核心问题':`${noteNumber(n)} · ${n.title}`,text:[revision.title,revision.body].filter(Boolean).join('\n'),reason:revision.reason||undefined}))),
  ...data.crossThoughts.flatMap(c=>c.anchorRevisions.map((revision,index)=>({id:`anchors:${c.id}:${index}`,kind:'调整关联',at:revision.at,ownerId:c.id,owner:`${crossCode(c)} · ${c.title||short(c.text,34)}`,text:`${revision.fromLabel||revision.from.join(' ↔ ')} → ${revision.toLabel||revision.to.join(' ↔ ')}`,reason:revision.reason||undefined})))
  ,...data.manuscripts.flatMap(m=>m.revisions.map((revision,index)=>({id:`manuscript:${m.id}:${index}`,kind:'文稿修改',at:revision.at,ownerId:ROOT,owner:`文稿 · ${m.title}`,text:revision.body,manuscriptId:m.id})))
 ].sort((a,b)=>(Date.parse(b.at)||0)-(Date.parse(a.at)||0));
 function anchorText(id:string){const n=data.notes.find(n=>n.id===id);if(n)return `${n.id===ROOT?'核心问题':noteNumber(n)} ${n.title}`;const c=data.crossThoughts.find(c=>c.id===id);if(c)return `${crossCode(c)} ${c.title||c.text||'未命名关联主题'}`;const t=ordinaryThoughts.find(t=>t.id===id);return t?`${t.ownerLabel} 的思考：${short(t.text,70)}`:'已删除板块';}
 const graphItems=[...data.notes.map(n=>({id:n.id,text:n.title,kind:n.kind,label:n.id===ROOT?'核心问题':n.kind==='question'?noteNumber(n)+' · 子问题':'独立回答'})),...shownCards.map(c=>({id:c.id,text:c.text,kind:'card',label:'来自卡片集'})),...data.crossThoughts.map(c=>({id:c.id,text:c.title||c.text,kind:'cross',label:crossCode(c)}))];
 const positions=useMemo(()=>{const p:Record<string,{x:number;y:number}>={};const depthGap=data.crossThoughts.length?600:370,rowGap=data.crossThoughts.length?330:185;let row=0;function visit(id:string,depth:number){const children=data.notes.filter(n=>n.parent===id).sort((a,b)=>a.kind===b.kind?a.order-b.order:a.kind==='question'?-1:1);if(!children.length){p[id]={x:depth*depthGap,y:row*rowGap};row++;return;}children.forEach(n=>visit(n.id,depth+1));p[id]={x:depth*depthGap,y:(p[children[0].id].y+p[children[children.length-1].id].y)/2};}data.notes.filter(n=>!n.parent).forEach(n=>visit(n.id,0));const center=p[ROOT]?.y||0;shownCards.forEach((c,i)=>p[c.id]={x:-360,y:center+(i-(shownCards.length-1)/2)*185});const anchorPosition=(id:string)=>p[id]||p[ordinaryThoughts.find(t=>t.id===id)?.ownerId||''];function placeCrossChildren(parentId:string,parent:{x:number;y:number},depth=1){const children=data.notes.filter(n=>n.parent===parentId).sort((a,b)=>a.kind===b.kind?a.order-b.order:a.kind==='question'?-1:1);children.forEach((n,i)=>{p[n.id]={x:parent.x+depth*370,y:parent.y+(i-(children.length-1)/2)*185};placeCrossChildren(n.id,p[n.id],1);});}let pending=data.crossThoughts.slice().sort((a,b)=>a.order-b.order);for(let pass=0;pass<=data.crossThoughts.length&&pending.length;pass++){const next:CrossThought[]=[];pending.forEach(c=>{const anchors=c.anchorIds.map(anchorPosition).filter(Boolean);if(anchors.length<c.anchorIds.length){next.push(c);return;}const x=anchors.length?anchors.reduce((sum,a)=>sum+a.x,0)/anchors.length:0;const y=anchors.length?anchors.reduce((sum,a)=>sum+a.y,0)/anchors.length:center;const sameCenter=data.crossThoughts.filter(other=>other.order<c.order&&p[other.id]&&Math.abs(p[other.id].x-x)<10&&Math.abs(p[other.id].y-y)<10).length;p[c.id]={x,y:y+sameCenter*155};placeCrossChildren(c.id,p[c.id]);});if(next.length===pending.length)break;pending=next;}pending.forEach((c,i)=>{p[c.id]={x:0,y:center+(i+1)*155};placeCrossChildren(c.id,p[c.id]);});return p;},[data]);
 const bounds=useMemo(()=>{const v=Object.values(positions);return {left:Math.min(0,...v.map(p=>p.x))-45,top:Math.min(0,...v.map(p=>p.y))-(data.links.length?145:50),right:Math.max(260,...v.map(p=>p.x+285))+45,bottom:Math.max(130,...v.map(p=>p.y+130))+50};},[positions,data.links.length]);
 function fit(){const z=Math.min(1,viewport.width/(bounds.right-bounds.left),viewport.height/(bounds.bottom-bounds.top));setZoom(z);setPan({x:(viewport.width-(bounds.right-bounds.left)*z)/2-bounds.left*z,y:(viewport.height-(bounds.bottom-bounds.top)*z)/2-bounds.top*z});}
 useEffect(()=>{fit();},[viewport.width,viewport.height,data.notes.length,shownCards.length,data.crossThoughts]);
 const ownerOf=(id:string)=>ordinaryThoughts.find(t=>t.id===id)?.ownerId||id;
 const edges=[...data.notes.filter(n=>n.parent).map(n=>({id:n.id,from:n.parent!,to:n.id,type:n.kind==='question'?'子问题':'回答'})),...data.links,...data.crossThoughts.flatMap(c=>c.anchorIds.map(id=>({id:`${c.id}:${id}`,from:ownerOf(id),to:c.id,type:'交叉'})))];
 const links=edges.filter(l=>l.from===selected||l.to===selected);
 const possible=card?suggestions(data,card):[];
 const relatedCrosses=selected?data.crossThoughts.filter(c=>c.id!==selected&&(c.anchorIds.includes(selected)||(note?.thoughts||[]).some(t=>c.anchorIds.includes(t.id)))):[];
 const selectedText=cross?.title||cross?.text||(selected?itemText(data,selected):'');
 const thoughts=card?.thoughts||note?.thoughts||cross?.thoughts||[];
 const replyingThought=thoughts.find(t=>t.id===replyingThoughtId),replyRecord=data.thoughtReplies.find(r=>r.thoughtId===replyingThoughtId);
 useEffect(()=>{if(!selected||!focusedThoughtId)return;const timer=window.setTimeout(()=>{document.querySelectorAll<HTMLElement>('[data-thought-id]').forEach(element=>{if(element.dataset.thoughtId===focusedThoughtId)element.scrollIntoView({block:'center',behavior:'smooth'});});},120);return()=>window.clearTimeout(timer);},[selected,focusedThoughtId]);
 function openItem(id:string,thoughtId?:string,replyId?:string){setSelected(id);setFocusedThoughtId(thoughtId||null);setReplyingThoughtId(replyId?thoughtId||null:null);}
 function openReading(id:string,thoughtId?:string){const reading=data.readingNotes.find(item=>item.id===id);if(!reading)return;setReadingInitialId(id);setReadingInitialThoughtId(thoughtId||null);const linked=reading.questionIds.find(questionId=>data.crossThoughts.some(item=>item.id===questionId)||data.notes.some(item=>item.id===questionId&&item.kind==='question'&&item.parent));if(linked){setStandaloneReadingId(null);setSelected(linked);}else{setSelected(null);setStandaloneReadingId(id);}}
 function openBook(id:string,location?:string,bookThoughtId?:string){setLibraryInitialId(id);setLibraryInitialLocation(location||null);setLibraryInitialBookThoughtId(bookThoughtId||null);setLibraryInitialDetachedThoughtId(null);setLibraryOpen(true);}
 function openDetachedBookThought(id:string){setLibraryInitialId(null);setLibraryInitialLocation(null);setLibraryInitialBookThoughtId(null);setLibraryInitialDetachedThoughtId(id);setLibraryOpen(true);}
 function openManuscript(id:string){setManuscriptInitialId(id);setManuscriptsOpen(true);}
 function openHistoryEntry(entry:HistoryEntry){
  setHistoryOpen(false);
  if(entry.manuscriptId){openManuscript(entry.manuscriptId);return;}
  const replyId=entry.id.startsWith('reply:')?entry.id.slice(6):undefined;
  const thoughtId=replyId?data.thoughtReplies.find(reply=>reply.id===replyId)?.thoughtId:entry.id.startsWith('thought:')?entry.id.slice(8):undefined;
  if(thoughtId){
   const reading=data.readingNotes.find(item=>item.thoughts.some(thought=>thought.id===thoughtId));if(reading){openReading(reading.id,thoughtId);return;}
   const bookThought=data.bookThoughts.find(item=>item.thoughts.some(thought=>thought.id===thoughtId));if(bookThought){if(bookThought.libraryBookId)openBook(bookThought.libraryBookId,bookThought.sourceLocation,bookThought.id);else openDetachedBookThought(bookThought.id);return;}
   openItem(entry.ownerId,thoughtId,replyId);return;
  }
  openItem(entry.ownerId);
 }
 return <main className="studio"><header className="studio-header"><button type="button" className="wordmark" aria-label="返回关系图" onClick={()=>{setSelected(null);setForm(null);setBoxOpen(false);}}>问<span>间</span><i/></button><Button variant="outline" className="search-jump" disabled={loading} onClick={()=>setSearchOpen(true)} aria-label="搜索"><Search/><span>搜索</span></Button><Button variant="outline" className="history-jump" disabled={loading} onClick={()=>setHistoryOpen(true)}><History/><span>修改记录</span></Button><Button variant="outline" className="manuscript-jump" disabled={loading} onClick={()=>{setManuscriptInitialId(null);setManuscriptsOpen(true);}}><FileText/><span>文稿</span></Button><Button variant="outline" className="library-jump" disabled={loading} onClick={()=>{setLibraryInitialId(null);setLibraryInitialLocation(null);setLibraryInitialBookThoughtId(null);setLibraryInitialDetachedThoughtId(null);setLibraryOpen(true);}}><Library/><span>书库</span></Button><div className="save-state" role="status">{loading?'读取中':saving?<><Loader2 className="spin" size={14}/>保存中</>:<><Check size={14}/>{storage==='nutstore'?'已保存到同步目录':storage==='local'?'已保存到本机':'已保存'}</>}</div><Button variant="outline" className="share-jump" disabled={loading||sharing} onClick={shareReadOnly}>{sharing?<Loader2 className="spin"/>:<Share2/>}<span>分享</span></Button><Button variant="outline" className="cross-jump" disabled={loading||saving} onClick={startCrossMode}><Network/>交叉思考</Button><Button variant="outline" className="capture-jump" aria-expanded={boxOpen} aria-controls="card-box" onClick={()=>setBoxOpen(v=>!v)}><Archive/>卡片集 <span>{data.cards.length}</span></Button></header>
 {error&&!selected&&!form&&!deleting&&<div role="alert" className="error-banner">{error}<Button variant="ghost" onClick={load} disabled={saving}>重新读取</Button></div>}
 <div className={"studio-columns "+(boxOpen?"box-open":"box-closed")}><section className="map-side"><div className="question-heading"><h1><button onClick={()=>setSelected(ROOT)}>我们该如何处理<br className="mobile-break"/>我们和世界的关系？</button></h1><div className="map-topline"><div className="map-legend"><span><i className="blue"/>问题</span><span><i className="green"/>回答</span><span><i className="amber"/>卡片</span></div><Button variant="ghost" onClick={()=>openForm('question',ROOT)} disabled={loading}><Plus/>添加子问题</Button></div></div>
 <div className="map-canvas" ref={graphRef} onPointerDown={e=>{if((e.target as Element).closest('[data-node],button'))return;drag.current={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(drag.current)setPan({x:drag.current.px+e.clientX-drag.current.x,y:drag.current.py+e.clientY-drag.current.y});}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}>
 <svg width="100%" height="100%" viewBox={`0 0 ${viewport.width} ${viewport.height}`} role="group" aria-label="核心问题与已确认联系的关系图"><defs><marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0L10 5L0 10" fill="#9aa5ba"/></marker></defs><g transform={`translate(${pan.x} ${pan.y}) scale(${zoom})`}>
 {edges.map(l=>{const a=positions[l.from],b=positions[l.to];if(!a||!b)return null;const right=b.x>=a.x;const ax=a.x+(right?260:0),bx=b.x+(right?0:260),ay=a.y+60,by=b.y+60;const free=data.links.some(x=>x.id===l.id),crossEdge=l.type==='交叉';const arc=Math.min(a.y,b.y)-120;const path=crossEdge?`M${a.x+130} ${a.y+62} L${b.x+130} ${b.y+62}`:free?`M${a.x+130} ${a.y} C${a.x+130} ${arc},${b.x+130} ${arc},${b.x+130} ${b.y}`:`M${ax} ${ay} C${ax+(right?70:-70)} ${ay},${bx+(right?-70:70)} ${by},${bx} ${by}`;return <g key={l.id}><path d={path} fill="none" stroke={crossEdge?'#a27b9d':l.type==='回答'?'#83a69d':'#a4aec1'} strokeWidth={crossEdge?'1.8':'1.5'} strokeDasharray={['子问题','回答'].includes(l.type)?undefined:'5 5'} markerEnd={crossEdge?undefined:'url(#arrow)'}/>{!crossEdge&&<text x={free?(a.x+b.x)/2+130:(ax+bx)/2} y={free?arc+10:(ay+by)/2-12} textAnchor="middle" className="edge-word">{l.type}</text>}</g>;})}
 {graphItems.map(n=>{const p=positions[n.id];if(!p)return null;const activate=()=>setSelected(n.id);return <g key={n.id} data-node="true" role="button" tabIndex={0} aria-label={n.label+'：'+n.text} className={'map-node '+n.kind+(n.id===ROOT?' root-node':'')} transform={`translate(${p.x} ${p.y})`} onClick={activate} onKeyDown={e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();activate();}}}><rect x="0" y="4" width="260" height="124" rx="9" className="node-shade"/><rect width="260" height="124" rx="9" className="node-surface"/>{n.kind==='cross'?<foreignObject x="18" y="14" width="224" height="24"><div className="node-cross-code">{n.label}</div></foreignObject>:<text x="18" y="29" className="node-kicker">{n.label}</text>}<foreignObject x="18" y="44" width="224" height="64"><div className="node-words">{n.text}</div></foreignObject></g>;})}</g></svg>
 {loading&&<div className="map-loading"><Loader2 className="spin"/>读取中</div>}
 <div className="map-controls"><Button variant="ghost" size="icon" aria-label="缩小关系图" onClick={()=>setZoom(z=>Math.max(.15,z-.15))}><Minus/></Button><span>{Math.round(zoom*100)}%</span><Button variant="ghost" size="icon" aria-label="放大关系图" onClick={()=>setZoom(z=>Math.min(2.5,z+.15))}><Plus/></Button><Button variant="ghost" size="icon" aria-label="查看完整关系图" onClick={fit}><Maximize/></Button></div></div>
 <div className="map-bottom"><span>{data.notes.filter(n=>n.kind==='question').length} 个问题 · {data.crossThoughts.length} 个交叉板块 · {shownCards.length} 张已连接卡片</span></div></section>
 {boxOpen&&<aside className="cardbox" id="card-box"><div className="box-heading"><div><Archive size={20}/><h2>卡片集</h2><span className="box-count">{data.cards.length}</span></div></div><form className="quick-note" onSubmit={captureCard}><Textarea ref={captureRef} aria-label="记下一个点子" placeholder="记下一个想法…" value={capture} onChange={e=>setCapture(e.target.value)} rows={4} required maxLength={100000}/><details className="capture-details"><summary>来源（可选）</summary><label>这段话来自<NativeSelect value={captureOrigin} onChange={e=>setCaptureOrigin(e.target.value)}>{origins.map(o=><NativeSelectOption key={o}>{o}</NativeSelectOption>)}</NativeSelect></label><Input aria-label="卡片具体来源" value={captureSource} onChange={e=>setCaptureSource(e.target.value)} placeholder="书名、页码、链接，或触发它的事"/></details><div className="quick-footer"><Button type="submit" disabled={loading||saving||!capture.trim()} size="sm"><Plus/>添加卡片</Button></div></form>
 <div className="box-list">{[...data.cards].reverse().map(c=>{const count=data.links.filter(l=>l.from===c.id||l.to===c.id).length;const hints=suggestions(data,c);return <button key={c.id} className="paper-card" onClick={()=>setSelected(c.id)}><span className="paper-top"><span>{when(c.at)}</span><ArrowUpRight size={16}/></span><p>{c.text}</p><div className="paper-foot"><span>{c.thoughts.length?`${c.thoughts.length} 条后续思考`:'尚未追加思考'}</span><span className={count?'linked-label':'loose-label'}>{count?<><Link2 size={12}/>{count} 处联系</>:'未连接'}</span></div>{hints.length>0&&<span className="paper-hint"><Lightbulb size={13}/>{hints.length} 条联系建议</span>}</button>;})}{!loading&&!data.cards.length&&<p className="empty-box">暂无卡片</p>}</div><div className="box-bottom"/></aside>}</div>
 {message&&<div className="feedback" role="status"><Check size={16}/>{message}</div>}
 <Dialog open={historyOpen} onOpenChange={setHistoryOpen}><DialogContent className="history-dialog"><DialogTitle>修改记录</DialogTitle><DialogDescription>{historyEntries.length} 条记录，最近的在前面</DialogDescription><div className="history-overview">{historyEntries.map(entry=><button key={entry.id} className="history-entry" onClick={()=>openHistoryEntry(entry)}><div className="history-entry-head"><span>{entry.kind}</span><time>{when(entry.at)}</time></div><strong>{entry.owner}</strong><p>{entry.text}</p>{entry.reason&&<aside><b>修改原因</b>{entry.reason}</aside>}<div className="history-entry-open">打开所属笔记 <ArrowUpRight size={14}/></div></button>)}{!loading&&!historyEntries.length&&<p className="history-empty">还没有修改记录</p>}</div></DialogContent></Dialog>
 <GlobalSearch open={searchOpen} onOpenChange={setSearchOpen} data={data} onOpenItem={openItem} onOpenReading={openReading} onOpenManuscript={openManuscript} onOpenBook={openBook} onOpenDetachedBookThought={openDetachedBookThought}/>
 <CloudLibrary open={cloudOpen} onOpenChange={setCloudOpen} onRestored={()=>{setSelected(null);setLibraryOpen(false);setManuscriptsOpen(false);void load();}}/>
 {standaloneReadingId&&<ReadingNotes key={`standalone:${standaloneReadingId}`} data={data} questionId={null} initialId={standaloneReadingId} initialThoughtId={readingInitialThoughtId} saving={saving} save={save} onClose={()=>setStandaloneReadingId(null)} onOpenBook={(bookId,sourceLocation)=>{setStandaloneReadingId(null);openBook(bookId,sourceLocation);}}/>}
 <Manuscripts open={manuscriptsOpen} initialId={manuscriptInitialId} onOpenChange={setManuscriptsOpen} data={data} saving={saving} save={save} onOpenQuestion={setSelected} onOpenReading={openReading}/>
 <LibraryReader open={libraryOpen} initialBookId={libraryInitialId} initialLocation={libraryInitialLocation} initialBookThoughtId={libraryInitialBookThoughtId} initialDetachedThoughtId={libraryInitialDetachedThoughtId} onOpenChange={setLibraryOpen} data={data} saving={saving} save={save} deleteBook={deleteLibraryBook}/>
 <Dialog open={!!selected} onOpenChange={v=>{if(!v)setSelected(null);}}><DialogContent className="immersive-window" aria-describedby={undefined} onInteractOutside={e=>e.preventDefault()}><Button variant="outline" className="modal-cross-access" onClick={startCrossMode}><Network/>交叉思考</Button><Button variant="outline" className="modal-card-access" onClick={()=>{setSelected(null);setBoxOpen(true);}}><Archive/>卡片集</Button><div className="sheet-heading"><span className="overline">{cross?crossCode(cross):card?'卡片集 / 卡片':note?.id===ROOT?'核心问题':note?.kind==='question'?noteNumber(note)+' / 子问题':'独立回答'}</span><DialogTitle>{card?'卡片':selectedText}</DialogTitle></div><div className="sheet-scroll">{card&&<blockquote className="original-card"><span>最初记录</span><p>{card.text}</p><footer>{when(card.at)} · {card.origin}</footer>{card.source&&<div className="source-line">来源：{card.source}</div>}</blockquote>}{cross&&<div className="cross-block-tools"><Button variant="outline" onClick={editCrossLinks}><Network/>调整关联板块</Button><div className="cross-anchor-list">{cross.anchorIds.map(id=><button key={id} onClick={()=>setSelected(ownerOf(id))}>{anchorText(id)}<ArrowUpRight size={13}/></button>)}</div>{cross.anchorIds.length<2&&<p>请调整关联板块，补充连接。</p>}{cross.anchorRevisions.length>0&&<details className="cross-history"><summary>关联变化 · {cross.anchorRevisions.length}</summary>{[...cross.anchorRevisions].reverse().map((r,i)=><p key={i}><span>{when(r.at)}</span>{r.from.map(id=>anchorText(id).split(' ')[0]).join(' ↔ ')} → {r.to.map(id=>anchorText(id).split(' ')[0]).join(' ↔ ')}</p>)}</details>}</div>}{cross?.text&&<blockquote className="original-card cross-original"><span>连接 {cross.anchorIds.length} 个位置</span><p>{cross.text}</p><footer>{when(cross.at)} · {cross.origin}</footer>{cross.source&&<div className="source-line">来源：{cross.source}</div>}</blockquote>}{note?.body&&<div className="original-note"><span>最初记录</span><p>{note.body}</p></div>}
 {(note?.kind==='question'||cross)&&<div className="question-actions">{note?.parent&&<Button variant="ghost" className="delete-question" onClick={()=>beginDelete(note.id)} disabled={saving}><Trash2/>删除子问题</Button>}<Button variant="outline" onClick={()=>openForm('question',selected!)}><GitBranch/>添加子问题</Button><Button variant="outline" onClick={()=>openForm('answer',selected!)}><MessageSquare/>添加回答</Button></div>}
 {(note||cross)&&data.notes.filter(n=>n.parent===selected).map(n=><button className="child-row" key={n.id} onClick={()=>setSelected(n.id)}><span>{n.kind==='question'?noteNumber(n):'回答'}</span><strong>{n.title}</strong><ArrowUpRight size={15}/></button>)}
 {relatedCrosses.length>0&&<section className="local-crosses"><h3><Network size={15}/>关联主题</h3>{relatedCrosses.map(c=><button key={c.id} onClick={()=>setSelected(c.id)}><span>{crossCode(c)}</span><p>{short(c.title||c.text,110)}</p><ArrowUpRight size={14}/></button>)}</section>}
 {((note?.kind==='question'&&note.parent)||cross)&&<ReadingNotes key={selected} data={data} questionId={selected!} initialId={readingInitialId} initialThoughtId={readingInitialThoughtId} saving={saving} save={save} onOpenBook={(bookId,sourceLocation)=>{setSelected(null);openBook(bookId,sourceLocation);}}/>}
 {note&&note.revisions.length>0&&<details className="legacy-history"><summary>此前的修订记录（{note.revisions.length}）</summary>{note.revisions.map((r,i)=><article key={i}><small>{when(r.at)} · {r.reason}</small><h4>{r.title}</h4><p>{r.body}</p><small>{r.origin} {r.source}</small></article>)}</details>}
 <section className="thought-stream"><h3>后来想到的 <span>{thoughts.length}</span></h3>{thoughts.map((t,i)=>{const reply=data.thoughtReplies.find(r=>r.thoughtId===t.id);return <button type="button" key={t.id} className={'thought-entry thought-entry-button'+(focusedThoughtId===t.id?' search-focus':'')} data-thought-id={t.id} onClick={()=>{setReplyingThoughtId(t.id);setReplyText('');}}><div className="thought-meta"><span>{String(i+1).padStart(2,'0')}</span>{when(t.at)} · {t.origin}</div><p>{t.text}</p>{t.reason&&<div className="change-reason"><strong>为什么改变判断</strong><p>{t.reason}</p></div>}<div className="thought-reply-state"><MessageSquare size={14}/>{reply?`已回答 · ${when(reply.at)}`:'回应这条思考'}</div></button>})}</section>
 <form className="append-form" onSubmit={addThought}><label htmlFor="new-thought">添加思考</label><Textarea id="new-thought" value={draft.text} onChange={e=>changeDraft({text:e.target.value})} placeholder="写下你的思考…" rows={10} required/><div className="thought-options"><NativeSelect aria-label="后续思考来源" value={draft.origin} onChange={e=>changeDraft({origin:e.target.value})}>{origins.map(o=><NativeSelectOption key={o}>{o}</NativeSelectOption>)}</NativeSelect><label className="change-toggle"><input type="checkbox" checked={draft.changed} onChange={e=>changeDraft({changed:e.target.checked})}/>我改变了原来的判断</label></div>{draft.changed&&<label className="reason-label">为什么改变？<Textarea value={draft.reason} onChange={e=>changeDraft({reason:e.target.value})} required rows={2} placeholder="是什么经历、材料或思考使你改变？"/></label>}<Button type="submit" disabled={saving||!draft.text.trim()}><CornerDownRight/>保存思考</Button></form>
 <details className="connections"><summary>联系 · {links.length}</summary><div className="section-heading"><h3>已经建立的联系 <span>{links.length}</span></h3><Button variant="ghost" size="sm" onClick={()=>selected&&openForm('link',selected)}><Plus/>手动连接</Button></div>{links.map(l=>{const other=l.from===selected?l.to:l.from;const explicit=data.links.some(x=>x.id===l.id);return <div className="connection-row" key={l.id}><button onClick={()=>setSelected(other)}><span>{l.from===selected?'→':'←'} {l.type}</span><p>{short(itemText(data,other),70)}</p></button>{explicit&&<Button variant="ghost" size="icon" disabled={saving} aria-label={'解除与'+short(itemText(data,other),20)+'的联系'} onClick={()=>save({...data,links:data.links.filter(x=>x.id!==l.id)},'已解除联系')}><Unlink size={14}/></Button>}</div>;})}{!links.length&&<p className="quiet-empty">暂无联系</p>}</details>
 {card&&<section className="suggestions"><h3><Lightbulb size={17}/>可能的联系 <span>待你确认</span></h3><p className="suggestion-note">基于词语和主题，确认后连线。</p>{possible.map(s=><article key={s.key}><strong>{itemText(data,s.to)}</strong><p>{s.reason}</p><div><Button variant="outline" size="sm" disabled={saving} onClick={()=>accept(s.from,s.to)}><Link2/>确认联系</Button><Button variant="ghost" size="sm" disabled={saving} onClick={()=>save({...data,dismissedSuggestions:[...data.dismissedSuggestions,s.key]},'已略过')}>略过</Button></div></article>)}{!possible.length&&<p className="quiet-empty">暂无建议</p>}</section>}
 {error&&<p role="alert" className="error-banner">{error}</p>}</div></DialogContent></Dialog>
 {crossPicker&&<CrossBlockPicker data={data} editing={data.crossThoughts.find(c=>c.id===editingCross)} saving={saving} error={error} onClose={closeCrossPicker} onSave={saveCrossBlock}/>}
 <Dialog open={!!form} onOpenChange={v=>{if(!v&&!saving)setForm(null);}}><DialogContent className="structure-dialog"><DialogTitle>{form?.kind==='link'?'建立一条联系':form?.kind==='answer'?'给这个问题一份回答':'添加一个子问题'}</DialogTitle><DialogDescription>{form?.kind==='link'?'选择关联的记录。':'所属问题：'+(form?itemText(data,form.from):'')}</DialogDescription><form onSubmit={submitForm} className="structure-form">{form?.kind==='link'?<><div className="link-from"><span>从</span>{short(itemText(data,form.from),90)}</div><label>关系<NativeSelect value={relation} onChange={e=>setRelation(e.target.value)}>{['相关','支持','反驳','启发'].map(t=><NativeSelectOption key={t}>{t}</NativeSelectOption>)}</NativeSelect></label><label>连接到<NativeSelect value={target} onChange={e=>setTarget(e.target.value)} required>{data.notes.filter(n=>n.id!==form.from).map(n=><NativeSelectOption key={n.id} value={n.id}>{n.kind==='question'?noteNumber(n):'回答'} · {n.title}</NativeSelectOption>)}{data.crossThoughts.filter(c=>c.id!==form.from).map(c=><NativeSelectOption key={c.id} value={c.id}>{crossCode(c)} · {short(c.title||c.text,50)}</NativeSelectOption>)}{data.cards.filter(c=>c.id!==form.from).map(c=><NativeSelectOption key={c.id} value={c.id}>卡片 · {short(c.text,50)}</NativeSelectOption>)}</NativeSelect></label></>:<><label>{form?.kind==='answer'?'回答标题':'子问题'}<Input value={title} onChange={e=>setTitle(e.target.value)} maxLength={300} required autoFocus/></label><label>展开记录（可选）<Textarea value={body} onChange={e=>setBody(e.target.value)} rows={4}/></label></>}{error&&<p className="error-banner" role="alert">{error}</p>}<div className="form-actions"><Button type="button" variant="ghost" disabled={saving} onClick={()=>{const id=form?.from;setForm(null);if(id)setSelected(id);}}>返回</Button><Button type="submit" disabled={saving}>{saving?<Loader2 className="spin"/>:<Check/>}{form?.kind==='link'?'建立联系':'保留下来'}</Button></div></form></DialogContent></Dialog>
 <AlertDialog open={!!deleting} onOpenChange={open=>{if(!open)cancelDelete();}}><AlertDialogContent className="delete-dialog"><AlertDialogTitle>{deleteStep===1?'删除子问题 · 1/2':'最后确认 · 2/2'}</AlertDialogTitle><AlertDialogDescription>{deleteStep===1?'请核对删除范围。':'此操作无法撤销，输入“删除”后才能执行。'}</AlertDialogDescription>{plan&&<><strong className="delete-title">{plan.target.title}</strong><p className="delete-scope">将删除 {plan.notes.filter(n=>n.kind==='question').length} 个问题、{plan.notes.filter(n=>n.kind==='answer').length} 份回答，并移除 {plan.readingNotes.length} 条阅读笔记与这些问题的关联，同时影响 {plan.crossThoughts.length} 条交叉思考。交叉板块及其中的笔记会保留，仅移除被删除的连接。卡片集中的卡片不会删除。</p><ul className="delete-list">{plan.notes.map(n=><li key={n.id}>{n.kind==='question'?noteNumber(n):'回答'} · {n.title}</li>)}</ul></>}{deleteStep===2&&<label className="delete-input">输入“删除”<Input value={deleteText} onChange={e=>setDeleteText(e.target.value)} autoComplete="off" disabled={saving}/></label>}{error&&<p className="error-banner" role="alert">{error}</p>}<div className="form-actions"><Button variant="outline" disabled={saving} onClick={cancelDelete}>取消</Button>{deleteStep===1?<Button variant="destructive" onClick={()=>setDeleteStep(2)}>确认范围，继续</Button>:<Button variant="destructive" disabled={saving||deleteText!=='删除'} onClick={deleteQuestion}>{saving?'删除中…':'永久删除'}</Button>}</div></AlertDialogContent></AlertDialog>
 <Dialog open={!!replyingThoughtId} onOpenChange={open=>{if(!open&&!saving){setReplyingThoughtId(null);setReplyText('');}}}><DialogContent className="thought-reply-dialog"><DialogTitle>回应这条思考</DialogTitle><DialogDescription>{replyingThought?`${when(replyingThought.at)} · ${replyingThought.origin}`:''}</DialogDescription>{replyingThought&&<blockquote>{replyingThought.text}</blockquote>}{replyRecord?<section className="saved-thought-reply"><span>我的回答 · {when(replyRecord.at)}</span><p>{replyRecord.text}</p></section>:<form onSubmit={saveThoughtReply}><label>我的回答<Textarea value={replyText} onChange={e=>setReplyText(e.target.value)} rows={7} autoFocus required placeholder="写下此刻对它的回应…"/></label>{error&&<p className="error-banner" role="alert">{error}</p>}<div className="form-actions"><Button type="button" variant="ghost" disabled={saving} onClick={()=>{setReplyingThoughtId(null);setReplyText('');}}>取消</Button><Button type="submit" disabled={saving||!replyText.trim()}><CornerDownRight/>保存回答</Button></div></form>}</DialogContent></Dialog>
 </main>;
}
