'use client';
import {useEffect,useRef,useState} from 'react';
import {RefreshCw,Cloud,FolderOpen} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
import {Button} from './ui/button';
import {Input} from './ui/input';
import {syncApi,syncNow,syncBooks,updateSync,resolveSync,type Envelope} from '@/lib/sync/client';
import {materialize,project,stable,type Conflict} from '@/lib/sync/core';
type Provider='oss'|'nutstore';
type Identity={provider:Provider;configured:boolean;verified?:boolean;target:string;username?:string;directory?:string;legacyFolder?:string|null;remoteHasData?:boolean};
export type SyncStatus={provider:Provider;phase:'off'|'pending'|'syncing'|'error'|'conflict'|'saved';text:string};
let latestStatus:SyncStatus={provider:'oss',phase:'off',text:'尚未连接同步'};
function publish(status:SyncStatus){latestStatus=status;window.dispatchEvent(new CustomEvent('wenjian-sync-status',{detail:status}));}
export function useSyncStatus(){const [status,setStatus]=useState(latestStatus);useEffect(()=>{setStatus(latestStatus);const update=(event:Event)=>setStatus((event as CustomEvent<SyncStatus>).detail);window.addEventListener('wenjian-sync-status',update);return()=>window.removeEventListener('wenjian-sync-status',update);},[]);return status;}
function message(error:unknown){return error instanceof Error?error.message:'同步暂时未完成';}
function label(value:unknown):string{if(value===null)return '删除这条记录';if(typeof value==='object'){const v=value as Record<string,unknown>;return String(v.title||v.bookTitle||v.book||v.text||v.quote||'记录');}return String(value);}
export function DeviceSync({open,onOpenChange,onSettings,preferredService}:{open:boolean;onOpenChange:(open:boolean)=>void;onSettings:()=>void;preferredService?:Provider}){
 const [state,setState]=useState<Envelope|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[conflicts,setConflicts]=useState<Conflict[]>([]),[identity,setIdentity]=useState<Identity>({provider:'oss',configured:false,target:''});
 const [service,setService]=useState<Provider>('oss'),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[editing,setEditing]=useState(false),[migrating,setMigrating]=useState(false),[notesProgress,setNotesProgress]=useState(''),[booksProgress,setBooksProgress]=useState('');
 const busyRef=useRef(false),editingRef=useRef(false),identityRef=useRef(identity),lastAttempt=useRef(0),failure=useRef(''),needsCheck=useRef(false),statusKey=useRef(''),snapshotKey=useRef('');
 editingRef.current=open&&editing;
 const status=(snapshot:Envelope,connection:Identity,issue=failure.current)=>{
  const provider=connection.provider||'oss';const key=[snapshot.version,snapshot.syncRevision,connection.target,connection.verified,connection.legacyFolder,issue,navigator.onLine].join('|');if(statusKey.current===key)return;statusKey.current=key;
  if(issue)return publish({provider,phase:'error',text:'同步需要处理'});
  if(!connection.configured||!connection.verified)return publish({provider,phase:'off',text:connection.configured?'连接待检查':'尚未连接同步'});
  if(snapshot.sync&&materialize(snapshot.sync,snapshot.data).conflicts.length)return publish({provider,phase:'conflict',text:'有版本需要选择'});
  const changed=snapshot.sync&&(snapshot.sync.pending.length||stable(project(snapshot.data))!==stable(snapshot.sync.observed));
  if(changed)return publish({provider,phase:'pending',text:snapshot.sync?.enabled?(navigator.onLine?'等待同步':'离线 · 等待同步'):'本机有修改 · 自动同步暂停'});
  if(Object.keys(snapshot.sync?.books?.errors||{}).length)return publish({provider,phase:'pending',text:'笔记已同步 · 部分书籍待上传'});
  publish({provider,phase:snapshot.sync?.lastSync?'saved':'off',text:snapshot.sync?.lastSync?(snapshot.sync.enabled?'笔记已同步':'笔记已同步 · 自动同步暂停'):'连接就绪 · 等待开始'});
 };
 const refresh=async()=>{const snapshot=await syncApi<Envelope>('local'),connection=await syncApi<Identity>('identity');identityRef.current=connection;setIdentity(connection);const key=snapshot.version+':'+(snapshot.syncRevision||0);if(snapshotKey.current!==key){snapshotKey.current=key;setState(snapshot);setConflicts(snapshot.sync?materialize(snapshot.sync,snapshot.data).conflicts:[]);}if(!busyRef.current)status(snapshot,connection);return {snapshot,connection};};
 const synchronize=async(start=false)=>{if(busyRef.current)return;busyRef.current=true;setBusy(true);setError('');setNotice('');setBooksProgress('');setNotesProgress('正在同步…');lastAttempt.current=Date.now();statusKey.current='';const provider=identityRef.current.provider;publish({provider,phase:'syncing',text:'正在同步'});let notesSaved=false;try{
  if(start)await updateSync(sync=>({...sync,enabled:true}));
  const progress=(item:{stage:'notes'|'books';message:string})=>{if(item.stage==='notes'){if(!notesSaved)setNotesProgress(item.message);}else setBooksProgress(item.message);};
  let result=await syncNow(progress);notesSaved=true;setNotesProgress('笔记已同步');setState(result);
  result=await syncBooks(result,progress);setState(result);setConflicts(materialize(result.sync!,result.data).conflicts);
  const count=Object.keys(result.sync?.books?.errors||{}).length;setBooksProgress(count?'部分书籍等待上传':'本机书籍已上传；其他设备可按需下载');
  failure.current='';needsCheck.current=false;status(result,identityRef.current,'');
 }catch(cause){failure.current=message(cause);needsCheck.current=[401,403].includes((cause as {code?:number}).code||0);setError((notesSaved?'笔记已同步。书籍或书籍目录尚未同步完成：':'')+failure.current);if(!notesSaved)setNotesProgress('笔记同步未完成，本机内容已保留');publish({provider,phase:'error',text:notesSaved?'笔记已同步 · 书籍需处理':'同步未完成'});}finally{busyRef.current=false;setBusy(false);await refresh().catch(()=>{});}};
 const synchronizeRef=useRef(synchronize);synchronizeRef.current=synchronize;
 useEffect(()=>{if(open){setMigrating(false);setPassword('');void refresh().then(({connection})=>{setService(preferredService||connection.provider);setUsername(connection.username||'');setEditing(!connection.verified||!!preferredService&&preferredService!==connection.provider);}).catch(cause=>setError(message(cause)));}else setPassword('');},[open,preferredService]);
 useEffect(()=>{let active=true;const check=async()=>{if(!active||document.visibilityState==='hidden'||busyRef.current||editingRef.current)return;try{const {snapshot,connection}=await refresh();const delay=connection.provider==='nutstore'?300000:60000;if(navigator.onLine&&connection.verified&&snapshot.sync?.enabled&&!needsCheck.current&&Date.now()-lastAttempt.current>=delay)await synchronizeRef.current();}catch{/* The hosted website has no native sync endpoint. */}};const timer=setInterval(()=>void check(),15000);const visible=()=>void check();document.addEventListener('visibilitychange',visible);window.addEventListener('online',visible);window.addEventListener('offline',visible);void check();return()=>{active=false;clearInterval(timer);document.removeEventListener('visibilitychange',visible);window.removeEventListener('online',visible);window.removeEventListener('offline',visible);};},[]);
 async function toggleAuto(){try{const next=await updateSync(sync=>({...sync,enabled:!sync.enabled}));setState(next);statusKey.current='';status(next,identityRef.current);}catch(cause){setError(message(cause));}}
 async function resolve(key:string,id:string){setError('');try{await resolveSync(key,id);await refresh();}catch(cause){setError(message(cause));}}
 async function connect(event?:React.FormEvent){event?.preventDefault();if(busyRef.current)return;setError('');setNotice('正在检查账号与读写权限…');setBusy(true);busyRef.current=true;try{const connection=await syncApi<Identity>('connect',{provider:service,username,password});identityRef.current=connection;setPassword('');failure.current='';needsCheck.current=false;statusKey.current='';await refresh();setEditing(false);setNotesProgress('');setBooksProgress('');setNotice('连接检查通过。');}catch(cause){setError(message(cause));setNotice('');}finally{setBusy(false);busyRef.current=false;await refresh().catch(()=>{});}}
 async function detach(){setBusy(true);busyRef.current=true;setError('');setNotice('正在备份本机资料…');try{const result=await syncApi<{backupPath:string}>('detach',{target:state?.sync?.target||''});failure.current='';needsCheck.current=false;setPassword('');await refresh();setMigrating(false);setEditing(true);setNotice('备份已保存在：'+result.backupPath+'。请连接新的资料库。');setNotesProgress('');setBooksProgress('');}catch(cause){setError(message(cause));setNotice('');}finally{setBusy(false);busyRef.current=false;await refresh().catch(()=>{});}}
 const ready=identity.verified&&service===identity.provider,books=state?.data.libraryBooks.filter(book=>book.storedFile&&['pdf','epub'].includes(book.format))||[],bookErrors=Object.entries(state?.sync?.books?.errors||{}).filter(([id])=>books.some(book=>book.id===id)),confirmed=!!(state?.sync?.lastSync||state?.sync?.published?.length||state?.sync?.received.length);
 return <Dialog open={open} onOpenChange={value=>{if(!busy)onOpenChange(value);}}><DialogContent className="device-sync-dialog"><DialogTitle><Cloud size={20}/>三端同步</DialogTitle><DialogDescription>笔记先保存在本机，书籍上传后可在其他设备按需下载。</DialogDescription>
 <div className="sync-summary"><strong>{identity.provider==='nutstore'?'坚果云':'阿里云 OSS'}</strong><span>{!identity.configured?'尚未连接':!identity.verified?'连接待检查':'连接就绪'}</span>{identity.username&&<small>{identity.username} · 问间资料库</small>}</div>
 {editing&&<><div className="sync-provider-tabs" aria-label="同步服务">{(['oss','nutstore'] as const).map(item=><button key={item} disabled={busy} aria-pressed={service===item} onClick={()=>{setService(item);setPassword('');setError('');}}>{item==='oss'?'阿里云 OSS':'坚果云'}</button>)}</div><form className="sync-connection" onSubmit={connect}>{service==='nutstore'?<><label>坚果云邮箱<Input type="email" value={username} required autoComplete="off" onChange={event=>setUsername(event.target.value)}/></label><label>应用密码<Input type="password" value={password} autoComplete="new-password" placeholder={identity.username===username.trim().toLowerCase()?'留空使用已保存的应用密码':'坚果云安全选项中的应用密码'} onChange={event=>setPassword(event.target.value)}/></label><small>使用独立目录「问间资料库」，不会混入 Obsidian 的目录。连接检查只写入一个检查文件，不上传笔记。</small></>:<p>使用已有 OSS 设置。<Button type="button" variant="ghost" disabled={busy} onClick={onSettings}>编辑 OSS 设置</Button></p>}<div className="device-sync-actions"><Button disabled={busy} type="submit">连接并检查</Button>{identity.verified&&<Button variant="ghost" disabled={busy} type="button" onClick={()=>{setService(identity.provider);setUsername(identity.username||'');setEditing(false);setError('');}}>取消</Button>}</div></form></>}
 {ready&&!editing&&<><div className="sync-record-status"><div><strong>笔记与批注</strong><span role="status">{notesProgress||(state?.sync?.lastSync?'上次同步：'+new Date(state.sync.lastSync).toLocaleString('zh-CN'):'等待首次同步')}</span></div><div><strong>书籍</strong><span role="status">{booksProgress||`${books.filter(book=>book.cloudFile).length} / ${books.length} 本已在云端`}</span></div></div>{!confirmed&&<p className="sync-first">{identity.remoteHasData?'云端已有资料。开始同步会合并本机与云端内容，冲突的版本会保留，由你选择。':'云端尚无笔记。开始同步会上传本机笔记和书籍。'}</p>}<div className="device-sync-actions"><Button disabled={busy} onClick={()=>void synchronize(!confirmed)}><RefreshCw className={busy?'spin':''}/>{confirmed?'立即同步':'开始同步'}</Button><Button variant="ghost" disabled={busy} onClick={()=>{setEditing(true);setService(identity.provider);setUsername(identity.username||'');setError('');}}>连接设置</Button></div><label className="sync-auto"><input type="checkbox" checked={!!state?.sync?.enabled} disabled={busy||!confirmed} onChange={()=>void toggleAuto()}/>自动同步<small>{state?.sync?.enabled?(identity.provider==='nutstore'?'前台每 5 分钟检查':'前台每分钟检查'):'已暂停，仍可立即同步'}</small></label></>}
 {bookErrors.length>0&&<section className="sync-book-errors"><strong>待上传书籍</strong>{bookErrors.map(([id,issue])=><p key={id}>《{books.find(book=>book.id===id)?.title}》<span>{issue}</span></p>)}<Button variant="outline" disabled={busy||!ready} onClick={()=>void synchronize()}>重试待上传书籍</Button></section>}
 {editing&&confirmed&&!migrating&&<Button className="sync-migrate-button" variant="ghost" disabled={busy} onClick={()=>setMigrating(true)}>更换资料库…</Button>}
 {migrating&&<section className="sync-migration"><strong>备份后更换资料库</strong><p>先备份本机笔记、草稿和书籍，再清除本机的旧连接与同步历史。本机内容和旧云端资料保留。新连接检查通过后，由你开始上传。</p><p>请先同步其他设备的未上传修改；更换时其他设备也需要连接新资料库。仅在云端的书籍须先下载，否则会停止更换。</p><div className="device-sync-actions"><Button disabled={busy} onClick={()=>void detach()}>备份并更换资料库</Button><Button variant="outline" disabled={busy} onClick={()=>setMigrating(false)}>取消</Button></div></section>}
 {identity.legacyFolder&&<section className="sync-legacy"><strong>原坚果云同步文件夹</strong><p>本机仍保留原目录副本；问间直接同步使用独立的资料库。</p><Button variant="outline" onClick={()=>void syncApi('open-folder',{}).catch(cause=>setError(message(cause)))}><FolderOpen/>打开同步目录</Button></section>}
 {notice&&<p role="status" className="sync-notice">{notice}</p>}{error&&<p role="alert" className="sync-error">{error}</p>}
 {!!conflicts.length&&<section><h3>{conflicts.length} 条记录需要选择版本</h3><p>所有版本均已保留，不会自动覆盖。</p>{conflicts.map(conflict=><article className="sync-conflict" key={conflict.key}>{conflict.options.map(option=><div key={option.id}><strong>{label(option.value)}</strong><small>{new Date(option.at).toLocaleString('zh-CN')} · 设备 {option.device.slice(0,8)}</small><details><summary>查看完整内容</summary><pre>{JSON.stringify(option.value,null,2)}</pre></details><Button variant="outline" disabled={busy} onClick={()=>void resolve(conflict.key,option.id)}>使用此版本</Button></div>)}</article>)}</section>}
 </DialogContent></Dialog>;
}
