'use client';
import {useEffect,useRef,useState} from 'react';
import {RefreshCw,Cloud,FolderOpen} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
import {Button} from './ui/button';
import {Input} from './ui/input';
import {syncApi,syncNow,resolveSync,type Envelope} from '@/lib/sync/client';
import {materialize,newSyncState,project,stable,type Conflict} from '@/lib/sync/core';
type Provider='oss'|'nutstore';
type Identity={provider:Provider;configured:boolean;target:string;username?:string;directory?:string;legacyFolder?:string|null};
export type SyncStatus={provider:Provider;phase:'off'|'pending'|'syncing'|'error'|'conflict'|'saved';text:string};
let latestStatus:SyncStatus={provider:'oss',phase:'off',text:'同步未开启'};
function publish(status:SyncStatus){latestStatus=status;window.dispatchEvent(new CustomEvent('wenjian-sync-status',{detail:status}));}
export function useSyncStatus(){const [status,setStatus]=useState(latestStatus);useEffect(()=>{setStatus(latestStatus);const update=(event:Event)=>setStatus((event as CustomEvent<SyncStatus>).detail);window.addEventListener('wenjian-sync-status',update);return()=>window.removeEventListener('wenjian-sync-status',update);},[]);return status;}
function message(error:unknown){return error instanceof Error?error.message:'同步暂时未完成';}
function label(value:unknown):string{if(value===null)return '删除这条记录';if(typeof value==='object'){const v=value as Record<string,unknown>;return String(v.title||v.bookTitle||v.book||v.text||v.quote||'记录');}return String(value);}
export function DeviceSync({open,onOpenChange,onSettings,preferredService}:{open:boolean;onOpenChange:(open:boolean)=>void;onSettings:()=>void;preferredService?:Provider}){
 const [state,setState]=useState<Envelope|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[conflicts,setConflicts]=useState<Conflict[]>([]),[identity,setIdentity]=useState<Identity>({provider:'oss',configured:false,target:''});
 const [service,setService]=useState<Provider>('oss'),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[editing,setEditing]=useState(false);
 const busyRef=useRef(false),identityRef=useRef(identity),lastAttempt=useRef(0),failure=useRef(''),statusKey=useRef(''),snapshotKey=useRef('');
 const status=(snapshot:Envelope,connection:Identity,issue=failure.current)=>{
  const provider=connection.provider||'oss';const key=[snapshot.version,snapshot.syncRevision,connection.target,connection.legacyFolder,issue,navigator.onLine].join('|');if(statusKey.current===key)return;statusKey.current=key;
  if(issue)return publish({provider,phase:'error',text:'同步未完成'});
  if(!snapshot.sync?.enabled)return publish({provider,phase:'off',text:connection.legacyFolder?'坚果云目录 · 云端状态待确认':'同步未开启'});
  if(materialize(snapshot.sync,snapshot.data).conflicts.length)return publish({provider,phase:'conflict',text:'有版本需要选择'});
  if(snapshot.sync.pending.length||stable(project(snapshot.data))!==stable(snapshot.sync.observed))return publish({provider,phase:'pending',text:navigator.onLine?'等待同步':'离线 · 等待同步'});
  publish({provider,phase:snapshot.sync.lastSync?'saved':'pending',text:snapshot.sync.lastSync?'笔记已同步':'等待首次同步'});
 };
 const refresh=async()=>{const snapshot=await syncApi<Envelope>('local'),connection=await syncApi<Identity>('identity');identityRef.current=connection;setIdentity(connection);const key=snapshot.version+':'+(snapshot.syncRevision||0);if(snapshotKey.current!==key){snapshotKey.current=key;setState(snapshot);setConflicts(snapshot.sync?materialize(snapshot.sync,snapshot.data).conflicts:[]);}if(!busyRef.current)status(snapshot,connection);return {snapshot,connection};};
 const synchronize=async()=>{if(busyRef.current)return;busyRef.current=true;setBusy(true);setError('');lastAttempt.current=Date.now();statusKey.current='';const provider=identityRef.current.provider;publish({provider,phase:'syncing',text:'正在同步'});try{
  setNotice('正在同步笔记…');let result=await syncNow();setState(result);const bookErrors:string[]=[];
  for(const book of result.data.libraryBooks){if(!book.storedFile||book.cloudFile||!['pdf','epub'].includes(book.format))continue;const local=await syncApi<{available:boolean}>('book',{action:'status',id:book.id});if(!local.available)continue;setNotice('正在上传《'+book.title+'》…');try{await syncApi('book',{action:'upload',target:result.sync?.target,id:book.id});}catch(cause){bookErrors.push('《'+book.title+'》：'+message(cause));break;}}
  result=await syncNow();setState(result);setConflicts(materialize(result.sync!,result.data).conflicts);
  if(bookErrors.length)throw Error('笔记已同步，部分书籍等待上传。'+bookErrors.join(' '));
  failure.current='';status(result,identityRef.current,'');setNotice('本次同步完成；云端书籍在打开时下载。');
 }catch(cause){failure.current=message(cause);setError(failure.current);setNotice('');publish({provider,phase:'error',text:'同步未完成'});}finally{busyRef.current=false;setBusy(false);}};
 useEffect(()=>{if(open){setEditing(false);setPassword('');void refresh().then(({connection})=>{setService(preferredService||connection.provider);setUsername(connection.username||'');setEditing(preferredService==='nutstore'||!connection.configured);}).catch(cause=>setError(message(cause)));}else setPassword('');},[open,preferredService]);
 useEffect(()=>{let active=true;const check=async()=>{if(!active||document.visibilityState==='hidden'||busyRef.current)return;try{const {snapshot,connection}=await refresh();const delay=connection.provider==='nutstore'?300000:60000;if(navigator.onLine&&snapshot.sync?.enabled&&Date.now()-lastAttempt.current>=delay)await synchronize();}catch{/* The hosted website has no native sync endpoint. */}};const timer=setInterval(()=>void check(),15000);const visible=()=>void check();document.addEventListener('visibilitychange',visible);window.addEventListener('online',visible);window.addEventListener('offline',visible);void check();return()=>{active=false;clearInterval(timer);document.removeEventListener('visibilitychange',visible);window.removeEventListener('online',visible);window.removeEventListener('offline',visible);};},[]);
 async function toggle(){try{const current=await syncApi<Envelope>('local'),sync=current.sync||newSyncState();sync.enabled=!sync.enabled;const next=await syncApi<Envelope>('commit',{version:current.version,syncRevision:current.syncRevision||0,data:current.data,sync});window.dispatchEvent(new CustomEvent('wenjian-sync-updated',{detail:next}));setState(next);failure.current='';setError('');status(next,identityRef.current,'');if(sync.enabled)await synchronize();}catch(cause){setError(message(cause));}}
 async function resolve(key:string,id:string){setError('');try{await resolveSync(key,id);await refresh();}catch(cause){setError(message(cause));}}
 async function saveConnection(event:React.FormEvent){event.preventDefault();setError('');setBusy(true);busyRef.current=true;try{await syncApi('settings',{provider:service,username,password});setPassword('');failure.current='';await refresh();setEditing(false);setNotice('连接已保存，请检测连接后开启同步。');}catch(cause){setError(message(cause));}finally{setBusy(false);busyRef.current=false;}}
 async function test(){setBusy(true);busyRef.current=true;setError('');try{await syncApi('test',{target:identity.target});setNotice('连接正常，可以开启同步。');}catch(cause){setError(message(cause));}finally{setBusy(false);busyRef.current=false;}}
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="device-sync-dialog"><DialogTitle><Cloud size={20}/>三端同步</DialogTitle><DialogDescription>共享笔记、批注、分类和书籍。离线时先保存在本机。</DialogDescription>
 <div className="sync-provider-tabs" aria-label="同步服务">{(['oss','nutstore'] as const).map(item=><button key={item} disabled={busy} aria-pressed={service===item} onClick={()=>{setService(item);setEditing(true);setNotice('');setError('');}}>{item==='oss'?'阿里云 OSS':'坚果云'}</button>)}</div>
 <div className="sync-summary"><strong>{service==='nutstore'?'坚果云':'阿里云 OSS'}</strong><span>{service!==identity.provider?'连接尚未保存':!identity.configured?'尚未配置':state?.sync?.enabled?'自动同步已开启':'自动同步已暂停'}</span>{service===identity.provider&&state?.sync?.lastSync&&<small>上次笔记同步：{new Date(state.sync.lastSync).toLocaleString('zh-CN')}</small>}</div>
 {(editing||service!==identity.provider)&&<form className="sync-connection" onSubmit={saveConnection}>{service==='nutstore'?<><label>坚果云邮箱<Input type="email" value={username} required autoComplete="off" onChange={event=>setUsername(event.target.value)}/></label><label>应用密码<Input type="password" value={password} autoComplete="new-password" placeholder={identity.username===username?'留空保留已存密码':'在坚果云的安全选项中生成'} onChange={event=>setPassword(event.target.value)}/></label><p>独立目录：问间资料库。使用坚果云的第三方应用密码。</p><small>单本书小于 500 MB；开启后，前台每 5 分钟检查一次，也可立即同步。</small></>:<p>沿用已有 OSS 连接。<Button type="button" variant="ghost" onClick={onSettings}>编辑 OSS 设置</Button></p>}<Button disabled={busy} type="submit">保存{service==='nutstore'?'坚果云':'OSS'}连接</Button>{state?.sync?.target&&<small>已有同步历史时，暂不切换资料库位置。</small>}</form>}
 <div className="device-sync-actions"><Button disabled={busy||!identity.configured||service!==identity.provider} onClick={()=>void toggle()}>{state?.sync?.enabled?'暂停自动同步':'开启三端同步'}</Button><Button variant="outline" disabled={busy||!state?.sync?.enabled||service!==identity.provider} onClick={()=>void synchronize()}><RefreshCw className={busy?'spin':''}/>立即同步</Button><Button variant="outline" disabled={busy||!identity.configured||service!==identity.provider} onClick={()=>void test()}>检测连接</Button><Button variant="ghost" disabled={busy} onClick={()=>{setEditing(!editing);setService(identity.provider);}}>连接设置</Button></div>
 {identity.legacyFolder&&<section className="sync-legacy"><strong>原坚果云同步文件夹</strong><p>本机已保存到此目录。是否上传完成，请以坚果云客户端为准。开启三端同步后，会保留原目录副本，并转为本机保存、由问间直接同步。</p><Button variant="outline" onClick={()=>void syncApi('open-folder',{}).catch(cause=>setError(message(cause)))}><FolderOpen/>打开同步目录</Button></section>}
 {notice&&<p role="status">{notice}</p>}{error&&<p role="alert" className="sync-error">{error}</p>}
 {!!conflicts.length&&<section><h3>{conflicts.length} 条记录需要选择版本</h3><p>以下版本均已保留在同步历史中，不会自动覆盖。</p>{conflicts.map(conflict=><article className="sync-conflict" key={conflict.key}>{conflict.options.map(option=><div key={option.id}><strong>{label(option.value)}</strong><small>{new Date(option.at).toLocaleString('zh-CN')} · 设备 {option.device.slice(0,8)}</small><details><summary>查看完整内容</summary><pre>{JSON.stringify(option.value,null,2)}</pre></details><Button variant="outline" disabled={busy} onClick={()=>void resolve(conflict.key,option.id)}>使用此版本</Button></div>)}</article>)}</section>}
 </DialogContent></Dialog>;
}
