'use client';

import {useEffect,useRef,useState} from 'react';
import {Check,FilePlus2,FileText,Link2,Unlink} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogDescription,DialogTitle} from '@/components/ui/dialog';
import {Input} from '@/components/ui/input';
import {readDraft,writeDraft} from '@/lib/draft-storage';
import {type Manuscript,type ManuscriptLink,type Notebook,numberOf,ROOT} from '@/lib/notebook';

type Props={open:boolean;initialId:string|null;onOpenChange:(open:boolean)=>void;data:Notebook;saving:boolean;save:(next:Notebook,feedback:string)=>Promise<boolean>;onOpenQuestion:(id:string)=>void;onOpenReading:(id:string)=>void};
type TextSelection={start:number;end:number;quote:string;left:number;top:number};
type ManuscriptDraft={kind:'manuscript';baseUpdatedAt:string|null;title:string;body:string;links:ManuscriptLink[];savedAt:string};
const draftKey=(id:string|null)=>`manuscript:${id||'new'}`;
const ACTIVE_DRAFT_KEY='manuscript:active';
const baseUpdatedAt=(manuscript?:Manuscript)=>manuscript?.updatedAt||manuscript?.at||null;
function validDraft(value:unknown):value is ManuscriptDraft{return !!value&&typeof value==='object'&&'kind' in value&&value.kind==='manuscript'&&'title' in value&&typeof value.title==='string'&&'body' in value&&typeof value.body==='string'&&'links' in value&&Array.isArray(value.links)&&value.links.every((link:unknown)=>!!link&&typeof link==='object'&&'id' in link&&typeof link.id==='string'&&'quote' in link&&typeof link.quote==='string'&&'start' in link&&typeof link.start==='number'&&'end' in link&&typeof link.end==='number')&&'baseUpdatedAt' in value&&(typeof value.baseUpdatedAt==='string'||value.baseUpdatedAt===null);}
function resolveLinks(text:string,editor:HTMLDivElement|null,links:ManuscriptLink[]){return links.map(link=>{const mark=[...(editor?.querySelectorAll<HTMLElement>('[data-link-ids]')||[])].find(element=>element.dataset.linkIds?.split(',').includes(link.id));if(mark&&editor){const before=document.createRange();before.selectNodeContents(editor);before.setEndBefore(mark);const start=before.toString().length,quote=mark.textContent||'';if(quote)return {...link,start,end:start+quote.length,quote,prefix:text.slice(Math.max(0,start-24),start),suffix:text.slice(start+quote.length,start+quote.length+24),unresolved:false};}const first=text.indexOf(link.quote),last=text.lastIndexOf(link.quote);if(link.quote&&first>=0&&first===last)return {...link,start:first,end:first+link.quote.length,prefix:text.slice(Math.max(0,first-24),first),suffix:text.slice(first+link.quote.length,first+link.quote.length+24),unresolved:false};return {...link,unresolved:true};});}

export function Manuscripts({open,initialId,onOpenChange,data,saving,save,onOpenQuestion,onOpenReading}:Props){
 const [selectedId,setSelectedId]=useState<string|null>(null),[title,setTitle]=useState(''),[body,setBody]=useState(''),[draftLinks,setDraftLinks]=useState<ManuscriptLink[]>([]),[selection,setSelection]=useState<TextSelection|null>(null),[picking,setPicking]=useState(false),[picked,setPicked]=useState<string[]>([]),[activeIds,setActiveIds]=useState<string[]>([]),[issue,setIssue]=useState(''),[renderKey,setRenderKey]=useState(0);
 const [draftReady,setDraftReady]=useState(false),[draftStatus,setDraftStatus]=useState<'idle'|'pending'|'saving'|'saved'|'error'>('idle'),[draftError,setDraftError]=useState(''),[staleDraft,setStaleDraft]=useState<ManuscriptDraft|null>(null);
 const editorRef=useRef<HTMLDivElement>(null);
 const caretAfterRef=useRef<number|null>(null);
 const loadTicket=useRef(0),draftWrites=useRef<Promise<void>>(Promise.resolve()),draftTimer=useRef<ReturnType<typeof setTimeout>|null>(null),baseVersionRef=useRef<string|null>(null);
 const manuscriptsRef=useRef(data.manuscripts),selectedIdRef=useRef(selectedId),renderBodyRef=useRef(body),renderLinksRef=useRef(draftLinks),persistDraftRef=useRef<()=>Promise<boolean>>(async()=>true),loadRef=useRef<(manuscript?:Manuscript,initialError?:string)=>Promise<void>>(async()=>{});
 const selected=data.manuscripts.find(m=>m.id===selectedId);
 const questions=data.notes.filter(n=>n.kind==='question');
 const activeLinks=draftLinks.filter(link=>activeIds.includes(link.id)&&!link.unresolved);
 const unresolved=draftLinks.filter(link=>link.unresolved);
 const dirty=selected?selected.title!==title||selected.body!==body||JSON.stringify(selected.links)!==JSON.stringify(draftLinks):!!(title.trim()||body.trim()||draftLinks.length);

 function editorText(){return (editorRef.current?.innerText||'').replace(/\r/g,'');}
 function queueDraft(key:string,value:unknown){const next=draftWrites.current.catch(()=>{}).then(()=>writeDraft(key,value));draftWrites.current=next;return next;}
 function draftSnapshot():ManuscriptDraft{return {kind:'manuscript',baseUpdatedAt:baseVersionRef.current,title,body,links:editorRef.current&&editorText()===body?resolveLinks(body,editorRef.current,draftLinks):draftLinks,savedAt:new Date().toISOString()};}
 async function persistDraft(){if(!draftReady||!dirty)return true;if(draftTimer.current){clearTimeout(draftTimer.current);draftTimer.current=null;}setDraftStatus('saving');try{await queueDraft(draftKey(selectedId),draftSnapshot());setDraftStatus('saved');setDraftError('');return true;}catch(error){const detail=(error as Error).message||'未知错误';setDraftStatus('error');setDraftError(`草稿保存失败：${detail}。请先正式保存文稿。`);return false;}}
 async function load(manuscript?:Manuscript,initialError=''){
  const ticket=++loadTicket.current;
  if(draftTimer.current){clearTimeout(draftTimer.current);draftTimer.current=null;}
  baseVersionRef.current=baseUpdatedAt(manuscript);
  setDraftReady(false);setStaleDraft(null);setDraftStatus('idle');setDraftError(initialError);setSelectedId(manuscript?.id||null);setTitle(manuscript?.title||'');setBody(manuscript?.body||'');setDraftLinks(manuscript?.links||[]);setSelection(null);setPicking(false);setPicked([]);setActiveIds([]);setIssue('');setRenderKey(key=>key+1);
  try{
   await draftWrites.current.catch(()=>{});
   const saved=await readDraft<unknown>(draftKey(manuscript?.id||null),null);
   if(ticket!==loadTicket.current)return;
   void queueDraft(ACTIVE_DRAFT_KEY,manuscript?.id||'new').catch(error=>setDraftError(`无法记录上次打开的文稿：${(error as Error).message||'未知错误'}。`));
   if(saved!==null&&!validDraft(saved)){setDraftError('草稿格式无法读取，当前显示已保存的文稿。');setDraftReady(true);return;}
   if(saved&&saved.baseUpdatedAt!==baseUpdatedAt(manuscript)){setStaleDraft(saved);setIssue('发现另一版本留下的草稿。请选择恢复或继续使用当前文稿。');return;}
   if(saved){setTitle(saved.title);setBody(saved.body);setDraftLinks(saved.links);setRenderKey(key=>key+1);setIssue('已恢复上次未保存的草稿。');setDraftStatus('saved');}
   setDraftReady(true);
  }catch(error){if(ticket!==loadTicket.current)return;setDraftError(`草稿读取失败：${(error as Error).message||'未知错误'}。仍可正式保存文稿。`);setDraftReady(true);}
 }
 async function requestLoad(manuscript?:Manuscript){if(!draftReady)return;if(dirty&&!await persistDraft())return;void load(manuscript);}
 async function closeWithDraft(afterClose?:()=>void){if(dirty&&!await persistDraft())return;onOpenChange(false);afterClose?.();}
 function requestClose(opened:boolean){if(opened){onOpenChange(true);return;}void closeWithDraft();}
 async function discardAndClose(){if(draftTimer.current){clearTimeout(draftTimer.current);draftTimer.current=null;}try{await queueDraft(draftKey(selectedId),null);setDraftError('');onOpenChange(false);}catch(error){setDraftError(`草稿删除失败：${(error as Error).message||'未知错误'}。请重试。`);}}
 async function ignoreStaleDraft(){try{await queueDraft(draftKey(selectedId),null);setStaleDraft(null);setIssue('');setDraftReady(true);}catch(error){setDraftError(`旧草稿删除失败：${(error as Error).message||'未知错误'}。`);}}
 function restoreStaleDraft(){if(!staleDraft)return;setTitle(staleDraft.title);setBody(staleDraft.body);setDraftLinks(staleDraft.links);setStaleDraft(null);setIssue('已恢复旧草稿，请核对后再保存。');setDraftReady(true);setRenderKey(key=>key+1);}
 useEffect(()=>{manuscriptsRef.current=data.manuscripts;selectedIdRef.current=selectedId;renderBodyRef.current=body;renderLinksRef.current=draftLinks;persistDraftRef.current=persistDraft;loadRef.current=load;});
 useEffect(()=>{if(!open){loadTicket.current++;return;}const manuscripts=manuscriptsRef.current;if(initialId){void loadRef.current(manuscripts.find(m=>m.id===initialId)||manuscripts[0]);return;}const ticket=++loadTicket.current;setDraftReady(false);void (async()=>{try{await draftWrites.current.catch(()=>{});const active=await readDraft<string|null>(ACTIVE_DRAFT_KEY,null);if(ticket!==loadTicket.current)return;const requested=active==='new'?undefined:manuscripts.find(m=>m.id===active)||manuscripts.find(m=>m.id===selectedIdRef.current)||manuscripts[0];void loadRef.current(requested);}catch(error){if(ticket!==loadTicket.current)return;void loadRef.current(manuscripts.find(m=>m.id===selectedIdRef.current)||manuscripts[0],`上次打开的文稿位置读取失败：${(error as Error).message||'未知错误'}。`);}})();},[open,initialId]);
 useEffect(()=>{if(!open||!draftReady||!dirty)return;setDraftStatus('pending');draftTimer.current=setTimeout(()=>{draftTimer.current=null;void persistDraftRef.current();},450);return()=>{if(draftTimer.current){clearTimeout(draftTimer.current);draftTimer.current=null;}};},[open,draftReady,selectedId,title,body,draftLinks,dirty]);
 useEffect(()=>{if(!open)return;const frame=requestAnimationFrame(()=>{const editor=editorRef.current;if(!editor)return;const currentBody=renderBodyRef.current,currentLinks=renderLinksRef.current;editor.replaceChildren();const groups=new Map<string,ManuscriptLink[]>();for(const link of currentLinks){if(link.unresolved||link.start<0||link.end>currentBody.length||link.start>=link.end)continue;const key=`${link.start}:${link.end}`;groups.set(key,[...(groups.get(key)||[]),link]);}const ordered=[...groups.values()].sort((a,b)=>a[0].start-b[0].start);let cursor=0,caretTarget:HTMLElement|null=null;for(const links of ordered){const {start,end}=links[0];if(start<cursor)continue;editor.appendChild(document.createTextNode(currentBody.slice(cursor,start)));const mark=document.createElement('span');mark.className='linked-sentence';mark.dataset.linkIds=links.map(link=>link.id).join(',');mark.contentEditable='false';mark.textContent=currentBody.slice(start,end);editor.appendChild(mark);if(caretAfterRef.current===end)caretTarget=mark;cursor=end;}editor.appendChild(document.createTextNode(currentBody.slice(cursor)));if(caretTarget){const range=document.createRange(),rangeSelection=window.getSelection();range.setStartAfter(caretTarget);range.collapse(true);rangeSelection?.removeAllRanges();rangeSelection?.addRange(range);editor.focus();caretAfterRef.current=null;}});return()=>cancelAnimationFrame(frame);},[open,selectedId,renderKey]);

 function inspectSelection(target?:EventTarget|null){const editor=editorRef.current,rangeSelection=window.getSelection();if(!editor||!rangeSelection||!rangeSelection.rangeCount)return;const range=rangeSelection.getRangeAt(0);if(!editor.contains(range.commonAncestorContainer))return;const node=rangeSelection.anchorNode;const clickedMark=target instanceof Element?target.closest<HTMLElement>('[data-link-ids]'):null;const mark=clickedMark||(node instanceof Element?node:node?.parentElement)?.closest<HTMLElement>('[data-link-ids]');if(range.collapsed||clickedMark){setSelection(null);setPicking(false);setActiveIds(mark?.dataset.linkIds?.split(',').filter(Boolean)||[]);return;}const before=document.createRange();before.selectNodeContents(editor);before.setEnd(range.startContainer,range.startOffset);const raw=range.toString();const leading=raw.length-raw.trimStart().length,quote=raw.trim();if(!quote)return;const text=editorText(),approximate=before.toString().length+leading,occurrences:number[]=[];for(let index=text.indexOf(quote);index>=0;index=text.indexOf(quote,index+1))occurrences.push(index);const start=occurrences.length?occurrences.reduce((best,value)=>Math.abs(value-approximate)<Math.abs(best-approximate)?value:best):approximate,rect=range.getBoundingClientRect();setSelection({start,end:start+quote.length,quote,left:Math.min(window.innerWidth-170,Math.max(16,rect.right+8)),top:Math.max(18,rect.top-44)});setPicked([]);setPicking(false);setActiveIds([]);setIssue('');}
 function beginLinking(){if(!selection)return;setPicking(true);setPicked([]);}
 function finishLinking(){if(!selection||!picked.length)return;const text=editorText();const overlaps=draftLinks.some(link=>!link.unresolved&&selection.start<link.end&&selection.end>link.start&&!(selection.start===link.start&&selection.end===link.end));if(overlaps){setIssue('这段文字与已有链接重叠，请重新选择。');return;}const at=new Date().toISOString();const next=draftLinks.filter(link=>!(link.unresolved&&picked.includes(link.questionId)));const created=picked.filter(targetId=>!next.some(link=>link.questionId===targetId&&link.start===selection.start&&link.end===selection.end)).map(targetId=>({id:crypto.randomUUID(),questionId:targetId,targetKind:data.readingNotes.some(note=>note.id===targetId)?'reading' as const:'question' as const,quote:selection.quote,start:selection.start,end:selection.end,prefix:text.slice(Math.max(0,selection.start-24),selection.start),suffix:text.slice(selection.end,selection.end+24),at}));caretAfterRef.current=selection.end;setBody(text);setDraftLinks([...next,...created]);setActiveIds([]);setSelection(null);setPicking(false);setPicked([]);setRenderKey(key=>key+1);}
 function removeLink(id:string){const text=editorText();setBody(text);setDraftLinks(links=>links.filter(link=>link.id!==id));setActiveIds(ids=>ids.filter(value=>value!==id));setRenderKey(key=>key+1);}
 function collectLinks(text:string){return resolveLinks(text,editorRef.current,draftLinks);}
 async function submit(e:React.FormEvent){e.preventDefault();const text=editorText();if(!title.trim()||!text.trim())return;const links=collectLinks(text),key=draftKey(selectedId),snapshot:ManuscriptDraft={kind:'manuscript',baseUpdatedAt:baseVersionRef.current,title,body:text,links,savedAt:new Date().toISOString()};if(draftTimer.current){clearTimeout(draftTimer.current);draftTimer.current=null;}try{await queueDraft(key,snapshot);setDraftError('');}catch(error){setDraftError(`草稿保存失败：${(error as Error).message||'未知错误'}。正在尝试正式保存文稿。`);}const now=new Date().toISOString();let next:Manuscript;if(selected){const changed=selected.title!==title.trim()||selected.body!==text||JSON.stringify(selected.links)!==JSON.stringify(links);next={...selected,title:title.trim(),body:text,links,updatedAt:changed?now:selected.updatedAt,revisions:changed?[...selected.revisions,{title:selected.title,body:selected.body,links:selected.links,at:selected.updatedAt||selected.at}]:selected.revisions};}else next={id:crypto.randomUUID(),title:title.trim(),body:text,links,at:now,updatedAt:now,revisions:[]};const manuscripts=selected?data.manuscripts.map(m=>m.id===next.id?next:m):[...data.manuscripts,next];if(await save({...data,manuscripts},selected?'文稿已更新':'文稿已创建')){baseVersionRef.current=baseUpdatedAt(next);setSelectedId(next.id);setBody(next.body);setDraftLinks(next.links);setDraftStatus('idle');setRenderKey(key=>key+1);try{await queueDraft(key,null);await queueDraft(ACTIVE_DRAFT_KEY,next.id);setDraftError('');}catch(error){setDraftError(`文稿已保存，但草稿记录清理失败：${(error as Error).message||'未知错误'}。`);}}else setIssue('正式保存未完成；本次内容已留在草稿中。');}
 function targetLabel(link:ManuscriptLink){if(link.targetKind==='reading'){const reading=data.readingNotes.find(note=>note.id===link.questionId);return reading?{number:'阅读',title:`《${reading.book}》${reading.chapter?` · ${reading.chapter}`:''}`,open:()=>onOpenReading(reading.id)}:null;}const question=data.notes.find(n=>n.id===link.questionId);return question?{number:link.questionId===ROOT?'核心':numberOf(question,data.notes,data.crossThoughts),title:question.title,open:()=>onOpenQuestion(link.questionId)}:null;}

 return <Dialog open={open} onOpenChange={requestClose}><DialogContent className="manuscript-dialog" aria-describedby={undefined}>
  <aside className="manuscript-list"><header><div><FileText size={18}/><DialogTitle>文稿</DialogTitle></div><Button size="icon" variant="ghost" aria-label="新建文稿" disabled={!draftReady} onClick={()=>requestLoad()}><FilePlus2/></Button></header><div>{data.manuscripts.map(m=><button type="button" key={m.id} className={m.id===selectedId?'is-current':''} disabled={!draftReady} onClick={()=>requestLoad(m)}><strong>{m.title}</strong><span>{new Date(m.updatedAt||m.at).toLocaleDateString('zh-CN')} · {m.links.length} 处句子关联</span></button>)}</div></aside>
  <form className="manuscript-workspace" onSubmit={submit}><DialogDescription>{selected?'继续写作':'新建文稿'} · 选中文字即可链接问题</DialogDescription><Input className="manuscript-title" value={title} onChange={e=>setTitle(e.target.value)} placeholder="文稿标题" maxLength={300} required disabled={!draftReady}/><div className="manuscript-paper"><div ref={editorRef} className="manuscript-editor" contentEditable={draftReady?'plaintext-only':false} suppressContentEditableWarning data-placeholder="从这里开始写作…" onInput={()=>{setIssue('');setBody(editorText());}} onMouseUp={()=>inspectSelection()} onKeyUp={()=>inspectSelection()} onClick={event=>inspectSelection(event.target)}/>
  {activeLinks.length>0&&<div className="manuscript-bubbles">{activeLinks.map(link=>{const target=targetLabel(link);if(!target)return null;return <div className="anchor-bubble" key={link.id}><button type="button" onClick={()=>void closeWithDraft(target.open)}><span>{target.number}</span>{target.title}</button><button type="button" aria-label={`解除与${target.title}的关联`} onClick={()=>removeLink(link.id)}><Unlink size={12}/></button></div>;})}</div>}</div>
  {selection&&!picking&&<Button type="button" size="sm" className="selection-linker" style={{left:selection.left,top:selection.top}} onClick={beginLinking}><Link2/>链接问题</Button>}
  {picking&&selection&&<div className="sentence-question-picker"><header><div><strong>这句话关联到</strong><p>“{selection.quote.length>70?selection.quote.slice(0,70)+'…':selection.quote}”</p></div><button type="button" onClick={()=>setPicking(false)}>取消</button></header><div><h4>问题</h4>{questions.map(question=><label key={question.id}><input type="checkbox" checked={picked.includes(question.id)} onChange={()=>setPicked(ids=>ids.includes(question.id)?ids.filter(id=>id!==question.id):[...ids,question.id])}/><span>{question.id===ROOT?'核心问题':numberOf(question,data.notes,data.crossThoughts)}</span>{question.title}</label>)}{!!data.readingNotes.length&&<h4>阅读笔记</h4>}{data.readingNotes.map(reading=><label key={reading.id}><input type="checkbox" checked={picked.includes(reading.id)} onChange={()=>setPicked(ids=>ids.includes(reading.id)?ids.filter(id=>id!==reading.id):[...ids,reading.id])}/><span>阅读</span><span>《{reading.book}》{reading.chapter?` · ${reading.chapter}`:''}<small>{reading.quote.slice(0,54)}{reading.quote.length>54?'…':''}</small></span></label>)}</div><Button type="button" onClick={finishLinking} disabled={!picked.length}><Check/>建立关联</Button></div>}
  <div className="manuscript-actions"><div>{!draftReady?<span className="unsaved-manuscript">{staleDraft?'发现旧草稿':'正在读取草稿…'}</span>:dirty?<span className="unsaved-manuscript">{draftStatus==='saved'?'草稿已自动保存':draftStatus==='saving'?'正在保存草稿…':'尚未正式保存'}</span>:unresolved.length>0?<span className="unresolved-count">{unresolved.length} 处关联待重新定位</span>:<span className="anchor-hint">选中文字，建立句子与问题的联系</span>}</div><div className="manuscript-save-actions">{dirty&&<Button type="button" variant="ghost" disabled={saving||!draftReady} onClick={()=>void discardAndClose()}>放弃修改</Button>}<Button type="submit" disabled={saving||!draftReady||!title.trim()||!body.trim()||!dirty}><Check/>保存文稿</Button></div></div>{issue&&<p className="manuscript-issue" role="status">{issue}</p>}{draftError&&<p className="manuscript-issue" role="alert">{draftError}</p>}{staleDraft&&<div className="manuscript-save-actions"><Button type="button" variant="outline" onClick={restoreStaleDraft}>恢复旧草稿</Button><Button type="button" variant="ghost" onClick={()=>void ignoreStaleDraft()}>使用当前文稿</Button></div>}</form>
 </DialogContent></Dialog>;
}
