'use client';
import {useLayoutEffect,useRef,useState,type ReactNode} from 'react';
import {ArrowDown,ArrowUp,ArrowUpRight,GripVertical,Link2,Plus,Trash2,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {materialKindLabel,materialSnapshot,sourceStatus,type ManuscriptBlock,type ManuscriptSourceSnapshot,type MaterialCatalog} from '@/lib/manuscript-materials';
import {moveManuscriptBlock,rebaseParagraphLinks} from '@/lib/manuscript-document';

export type ParagraphSelection={blockId:string;start:number;end:number;quote:string;left:number;top:number};
type Props={blocks:ManuscriptBlock[];catalog:MaterialCatalog;disabled:boolean;onChange:(blocks:ManuscriptBlock[],group?:string)=>void;onSelect:(selection:ParagraphSelection|null)=>void;onOpenSource:(source:ManuscriptSourceSnapshot)=>void;renderLinks:(block:ManuscriptBlock)=>ReactNode};
function ParagraphText({block,index,disabled,onChange,onSelect,onFocus}:{block:ManuscriptBlock;index:number;disabled:boolean;onChange:(text:string)=>void;onSelect:(selection:ParagraphSelection|null)=>void;onFocus:()=>void}){
 const ref=useRef<HTMLTextAreaElement>(null);
 useLayoutEffect(()=>{const element=ref.current;if(!element)return;const resize=()=>{element.style.height='0px';element.style.height=`${element.scrollHeight+2}px`;};resize();let width=element.getBoundingClientRect().width;const observer=new ResizeObserver(()=>{const next=element.getBoundingClientRect().width;if(next!==width){width=next;resize();}});observer.observe(element);return()=>observer.disconnect();},[block.text]);
 const select=(clientX?:number,clientY?:number)=>{const element=ref.current;if(!element)return;const start=element.selectionStart,end=element.selectionEnd,quote=element.value.slice(start,end);if(start===end||!quote.trim()){onSelect(null);return;}const rect=element.getBoundingClientRect();onSelect({blockId:block.id,start,end,quote,left:Math.min(window.innerWidth-170,Math.max(16,clientX??rect.left+50)),top:Math.max(20,Math.min(window.innerHeight-70,(clientY??rect.top)-45))});};
 return <textarea ref={ref} className="assembly-text" aria-label={`${block.kind==='heading'?'小标题':'文稿段落'} ${index+1}`} rows={1} value={block.text} disabled={disabled} placeholder={block.kind==='heading'?'写一个小标题…':'在这里继续写…'} onFocus={onFocus} onChange={event=>onChange(event.target.value)} onMouseUp={event=>select(event.clientX,event.clientY)} onKeyUp={()=>select()}/>;
}
export function ManuscriptAssembly({blocks,catalog,disabled,onChange,onSelect,onOpenSource,renderLinks}:Props){
 const [sourceId,setSourceId]=useState<string|null>(null),[focusedId,setFocusedId]=useState<string|null>(null),[dragged,setDragged]=useState<string|null>(null),[overId,setOverId]=useState<string|null>(null),[confirmReplace,setConfirmReplace]=useState(false);
 const sourceBlock=blocks.find(block=>block.id===sourceId),source=sourceBlock?.source;
 const status=source?sourceStatus(source,catalog):'current',current=source?catalog.materials.find(material=>material.key===source.key):undefined;
 const update=(id:string,patch:Partial<ManuscriptBlock>,group?:string)=>onChange(blocks.map(block=>block.id===id?{...block,...patch}:block),group);
 function append(kind:'paragraph'|'heading',after?:string){const block:ManuscriptBlock={id:crypto.randomUUID(),kind,text:'',links:[]};const next=[...blocks];next.splice(after?next.findIndex(item=>item.id===after)+1:next.length,0,block);onChange(next);setFocusedId(block.id);requestAnimationFrame(()=>document.querySelector<HTMLTextAreaElement>(`[data-paragraph-id="${block.id}"] textarea`)?.focus());}
 function useCurrent(){if(!sourceBlock||!current)return;if(sourceBlock.text!==source?.text&&!confirmReplace){setConfirmReplace(true);return;}update(sourceBlock.id,{text:current.text,source:materialSnapshot(current),links:rebaseParagraphLinks(sourceBlock.text,current.text,sourceBlock.links||[])});setConfirmReplace(false);}
 return <div className="assembly-workspace"><div className="assembly-paper">
  {blocks.map((block,index)=><section key={block.id} data-paragraph-id={block.id} data-kind={block.kind} className={'assembly-block'+(overId===block.id?' is-drop-target':'')}
    onDragOver={event=>{if(dragged){event.preventDefault();setOverId(block.id);}}} onDrop={event=>{event.preventDefault();if(dragged)onChange(moveManuscriptBlock(blocks,dragged,block.id));setDragged(null);setOverId(null);}}>
   <div className="assembly-block-tools"><button type="button" draggable={!disabled} aria-label={`拖动段落 ${index+1}`} title="拖动调整顺序" onDragStart={event=>{event.dataTransfer.setData('text/plain',block.id);event.dataTransfer.effectAllowed='move';setDragged(block.id);}} onDragEnd={()=>{setDragged(null);setOverId(null);}}><GripVertical size={14}/></button><button type="button" aria-label={`上移段落 ${index+1}`} title="上移" disabled={disabled||index===0} onClick={()=>onChange(moveManuscriptBlock(blocks,block.id,blocks[index-1].id))}><ArrowUp size={13}/></button><button type="button" aria-label={`下移段落 ${index+1}`} title="下移" disabled={disabled||index===blocks.length-1} onClick={()=>onChange(moveManuscriptBlock(blocks,block.id,blocks[index+1].id))}><ArrowDown size={13}/></button><button type="button" aria-label={`在段落 ${index+1} 后补写`} title="在后面补写" disabled={disabled} onClick={()=>append('paragraph',block.id)}><Plus size={13}/></button><button type="button" aria-label={`移除段落 ${index+1}`} title="移出文稿" disabled={disabled} onClick={()=>onChange(blocks.filter(item=>item.id!==block.id))}><Trash2 size={13}/></button></div>
   <ParagraphText block={block} index={index} disabled={disabled} onFocus={()=>setFocusedId(block.id)} onChange={text=>{onSelect(null);update(block.id,{text,links:rebaseParagraphLinks(block.text,text,block.links||[])},block.id);}} onSelect={onSelect}/>
   {block.source&&<button type="button" className="assembly-source-marker" data-status={sourceStatus(block.source,catalog)} aria-label={`查看段落 ${index+1} 的来源`} aria-expanded={sourceId===block.id} title={materialKindLabel[block.source.kind]+(sourceStatus(block.source,catalog)==='changed'?' · 来源有更新':sourceStatus(block.source,catalog)==='missing'?' · 保留的来源副本':'')} onClick={()=>{onSelect(null);setSourceId(id=>id===block.id?null:block.id);setConfirmReplace(false);}}><Link2 size={13}/></button>}
   {block.kind==='quote'&&block.source?.citation&&<div className="assembly-quote-citation">{block.source.citation}</div>}
   {focusedId===block.id&&renderLinks(block)}
  </section>)}
  {!blocks.length&&<p className="assembly-empty">加入已有笔记，或写下第一段。</p>}
  <div className="assembly-insert-actions"><Button type="button" size="sm" variant="ghost" disabled={disabled} onClick={()=>append('paragraph')}><Plus/>补写一段</Button><Button type="button" size="sm" variant="ghost" disabled={disabled} onClick={()=>append('heading')}><Plus/>添加小标题</Button></div>
 </div>
 {source&&sourceBlock&&<aside className="assembly-source-panel" aria-label="段落来源"><header><strong>段落来源</strong><Button type="button" size="icon" variant="ghost" aria-label="收起段落来源" onClick={()=>setSourceId(null)}><X size={16}/></Button></header><div className="assembly-source-body"><small>{materialKindLabel[source.kind]}{source.at?` · ${new Date(source.at).toLocaleString('zh-CN')}`:''}</small><h3>{source.label}</h3>{source.citation&&<p className="assembly-source-citation">{source.citation}</p>}{source.origin&&<small>{source.origin}</small>}<p className="assembly-source-original">{source.text}</p>{source.reason&&<p>修改原因：{source.reason}</p>}{status==='missing'&&<p className="assembly-status">原记录已不可用，这里保留加入文稿时的原话与出处。</p>}{status==='changed'&&current&&<section className="assembly-source-update"><strong>来源有更新</strong><p className="assembly-source-original">{current.text}</p>{current.citation&&<small>{current.citation}</small>}{confirmReplace&&<p role="status">本段已被你改写。替换会覆盖本段的文稿文字，可以用“撤销”恢复。</p>}<Button type="button" size="sm" variant="outline" disabled={disabled} onClick={useCurrent}>{confirmReplace?'确认替换本段':'采用当前原文'}</Button>{confirmReplace&&<Button type="button" size="sm" variant="ghost" onClick={()=>setConfirmReplace(false)}>取消</Button>}</section>}<Button type="button" size="sm" variant="ghost" disabled={status==='missing'} onClick={()=>onOpenSource(source)}>打开原记录<ArrowUpRight size={14}/></Button></div></aside>}
 </div>;
}
