import { env } from 'cloudflare:workers';
import { initialNotebook } from '@/lib/notebook';
import { z } from 'zod';
const revision=z.object({title:z.string().max(300),body:z.string().max(100000),origin:z.string().max(100),source:z.string().max(10000),reason:z.string().max(10000),at:z.string()});
const note=z.object({id:z.string().max(100),kind:z.enum(['question','answer']),parent:z.string().nullable(),order:z.number().int().positive(),title:z.string().trim().min(1).max(300),body:z.string().max(100000),origin:z.string().max(100),source:z.string().max(10000),revisions:z.array(revision).max(1000)});
const schema=z.object({version:z.number().int().nonnegative(),data:z.object({notes:z.array(note).max(3000),links:z.array(z.object({id:z.string(),from:z.string(),to:z.string(),type:z.enum(['相关','支持','反驳','启发'])})).max(10000)})});
function db(){if(!env.DB)throw new Error('Database unavailable');return env.DB;}
export async function GET(){try{const d=db();await d.prepare('INSERT OR IGNORE INTO notebooks(id,version,content) VALUES(?,0,?)').bind('personal',JSON.stringify(initialNotebook)).run();const row=await d.prepare('SELECT version,content FROM notebooks WHERE id=?').bind('personal').first<{version:number;content:string}>();return Response.json({version:row!.version,data:JSON.parse(row!.content)},{headers:{'Cache-Control':'no-store'}});}catch(e){console.error(e);return Response.json({error:'笔记暂时无法读取，请稍后重试。'},{status:503});}}
export async function PUT(req:Request){try{if(req.headers.get('origin') && req.headers.get('origin')!==new URL(req.url).origin)return Response.json({error:'无效请求来源'},{status:403});const parsed=schema.safeParse(await req.json());if(!parsed.success)return Response.json({error:'笔记格式不正确或内容超出容量。'},{status:400});const {data,version}=parsed.data;const ids=new Set(data.notes.map(n=>n.id));if(ids.size!==data.notes.length)throw new Error('Duplicate id');for(const n of data.notes){if(n.parent && !data.notes.some(p=>p.id===n.parent&&p.kind==='question'))throw new Error('Invalid parent');if(n.kind==='answer'&&!n.parent)throw new Error('Missing question');let p=n;const visited=new Set<string>();while(p.parent){if(visited.has(p.id))throw new Error('Cycle');visited.add(p.id);p=data.notes.find(x=>x.id===p.parent)!;}}for(const l of data.links)if(!ids.has(l.from)||!ids.has(l.to)||l.from===l.to)throw new Error('Invalid relation');const result=await db().prepare('UPDATE notebooks SET content=?,version=version+1 WHERE id=? AND version=?').bind(JSON.stringify(data),'personal',version).run();if(!result.meta.changes)return Response.json({error:'另一窗口已更新笔记。请先复制当前输入，再刷新页面。'},{status:409});return Response.json({version:version+1});}catch(e){console.error(e);return Response.json({error:'保存未完成，输入已保留，请重试。'},{status:503});}}
