import {type Manuscript,type Notebook,crossNumber,crossSignature,numberOf,ROOT} from './notebook';

const escape=(value:string)=>value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
const para=(value:string)=>escape(value).replace(/\n/g,'<br>');
export function readOnlyHtml(data:Notebook){
 const noteLabel=(id:string)=>{const note=data.notes.find(n=>n.id===id);return note?(id===ROOT?'核心问题':numberOf(note,data.notes,data.crossThoughts)):'原问题';};
 const thought=(t:{id:string;text:string;reason:string;at:string})=>{const reply=data.thoughtReplies.find(r=>r.thoughtId===t.id);return `<blockquote><time>${escape(new Date(t.at).toLocaleString('zh-CN'))}</time>${para(t.text)}${t.reason?`<aside>修改原因：${para(t.reason)}</aside>`:''}${reply?`<aside>我的回答：${para(reply.text)}</aside>`:''}</blockquote>`;};
 const itemLabel=(id:string)=>{const note=data.notes.find(n=>n.id===id);if(note)return `${noteLabel(id)} ${note.title}`;const card=data.cards.find(c=>c.id===id);if(card)return `卡片 ${capped(card.text)}`;const cross=data.crossThoughts.find(c=>c.id===id);return cross?`${crossNumber(cross)} ${cross.title||cross.text}`:'原记录';};
 const notes=data.notes.map(note=>`<article id="note-${escape(note.id)}"><small>${escape(note.id===ROOT?'核心问题':note.kind==='question'?numberOf(note,data.notes,data.crossThoughts)+' · 问题':'回答')}</small><h2>${escape(note.title)}</h2>${note.body?`<p>${para(note.body)}</p>`:''}${(note.thoughts||[]).map(thought).join('')}</article>`).join('');
 const crosses=data.crossThoughts.map(c=>`<article><small>${escape(crossNumber(c)+'〔'+crossSignature(c,data)+'〕')}</small><h2>${escape(c.title||'交叉思考')}</h2>${c.text?`<p>${para(c.text)}</p>`:''}${c.thoughts.map(thought).join('')}</article>`).join('');
 const readings=data.readingNotes.map(r=>`<article id="reading-${escape(r.id)}"><small>${r.questionIds.map(noteLabel).map(escape).join(' · ')}</small><h2>《${escape(r.book)}》${r.chapter?' · '+escape(r.chapter):''}</h2><blockquote>${para(r.quote)}</blockquote><p>${para(r.interpretation)}</p>${r.thoughts.map(thought).join('')}</article>`).join('');
 const bookThoughts=data.bookThoughts.map(entry=>`<article><small>${entry.questionIds.map(noteLabel).map(escape).join(' · ')||'本书思考'}${entry.locator?' · '+escape(entry.locator):''}</small><h2>《${escape(entry.bookTitle)}》</h2><p>${para(entry.text)}</p>${entry.thoughts.map(thought).join('')}</article>`).join('');
 const cards=data.cards.map(c=>`<article><small>卡片</small><p>${para(c.text)}</p>${c.thoughts.map(thought).join('')}</article>`).join('');
 const links=data.links.map(link=>`<li><span>${escape(link.type)}</span>${escape(itemLabel(link.from))} → ${escape(itemLabel(link.to))}</li>`).join('');
 const manuscripts=data.manuscripts.map(m=>`<article class="manuscript"><small>文稿</small><h2>${escape(m.title)}</h2><p>${linkedManuscript(m,data,noteLabel)}</p>${m.links.some(link=>link.unresolved)?`<aside>${m.links.filter(link=>link.unresolved).length} 处关联待重新定位</aside>`:''}</article>`).join('');
 return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>问间 · 只读副本</title><style>body{margin:0;background:#f5f7f8;color:#293947;font:16px/1.85 -apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif}main{max-width:900px;margin:auto;padding:64px 28px 100px}header{border-bottom:1px solid #dce4e8;margin-bottom:42px;padding-bottom:24px}h1{font:500 34px/1.5 "Songti SC",serif;margin:0}header p,small,time{color:#84939d;font-size:12px}section{margin-top:48px}section>h2{font-size:15px;letter-spacing:.12em;color:#617887}article{background:#fff;border:1px solid #e1e7ea;border-radius:10px;padding:24px 28px;margin:14px 0}article h2{font:500 22px/1.6 "Songti SC",serif}article p,blockquote{white-space:normal}blockquote{border-left:2px solid #9aadb8;margin:18px 0;padding:7px 0 7px 18px}blockquote time{display:block;margin-bottom:6px}blockquote aside{background:#f2f5f6;padding:9px 12px;margin-top:8px;font-size:13px;color:#6e7d86}.manuscript p{font:17px/2 "Songti SC",serif}.manuscript>aside{color:#9a725d;font-size:12px}.text-link{border-bottom:1px dotted #7695a6;background:linear-gradient(transparent 78%,#dce9ee 78%)}.text-link a{display:inline-grid;place-items:center;min-width:15px;height:15px;margin-left:2px;border-radius:50%;background:#668698;color:#fff;text-decoration:none;font:10px/1 sans-serif;vertical-align:super}.chips{display:flex;flex-wrap:wrap;gap:7px;margin:10px 0 18px}.chips a{background:#edf3f5;color:#5b7484;border-radius:18px;padding:3px 10px;font-size:12px;text-decoration:none}.links{padding:0;list-style:none}.links li{padding:11px 0;border-bottom:1px solid #e2e8eb}.links span{display:inline-block;margin-right:10px;color:#6b8493;font-size:12px}@media(max-width:600px){main{padding:36px 16px 70px}article{padding:20px}}</style></head><body><main><header><h1>我们该如何处理我们和世界的关系？</h1><p>问间只读副本 · ${escape(new Date().toLocaleString('zh-CN'))}</p></header>${manuscripts?`<section><h2>文稿</h2>${manuscripts}</section>`:''}<section><h2>问题与思考</h2>${notes}</section>${crosses?`<section><h2>交叉思考</h2>${crosses}</section>`:''}${links?`<section><h2>已建立的联系</h2><ul class="links">${links}</ul></section>`:''}${readings?`<section><h2>阅读笔记</h2>${readings}</section>`:''}${bookThoughts?`<section><h2>本书思考</h2>${bookThoughts}</section>`:''}${cards?`<section><h2>卡片集</h2>${cards}</section>`:''}</main></body></html>`;
}
function capped(value:string){return value.length>34?value.slice(0,34)+'…':value;}
function linkedManuscript(manuscript:Manuscript,data:Notebook,label:(id:string)=>string){const groups=new Map<string,typeof manuscript.links>();for(const link of manuscript.links){if(link.unresolved||link.start<0||link.end>manuscript.body.length||link.start>=link.end)continue;const key=`${link.start}:${link.end}`;groups.set(key,[...(groups.get(key)||[]),link]);}const ordered=[...groups.values()].sort((a,b)=>a[0].start-b[0].start);let cursor=0,result='';for(const links of ordered){const {start,end}=links[0];if(start<cursor)continue;result+=para(manuscript.body.slice(cursor,start));result+=`<span class="text-link">${para(manuscript.body.slice(start,end))}${links.map((link,index)=>{const reading=link.targetKind==='reading'?data.readingNotes.find(note=>note.id===link.questionId):undefined;const title=reading?`阅读笔记 · 《${reading.book}》${reading.chapter?' · '+reading.chapter:''}`:label(link.questionId);const href=reading?`#reading-${escape(reading.id)}`:`#note-${escape(link.questionId)}`;return `<a href="${href}" title="${escape(title)}">${index+1}</a>`;}).join('')}</span>`;cursor=end;}return result+para(manuscript.body.slice(cursor));}
