import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const sdk=process.env.ANDROID_HOME||path.join(root,'work/android-tools/sdk');
const javaHome=process.env.JAVA_HOME||path.join(root,'work/android-tools/jdk-21.0.12.1+1/Contents/Home');
const signing=path.join(root,'work/android-tools/signing');
const keystore=process.env.WENJIAN_ANDROID_KEYSTORE||path.join(signing,'wenjian-reader-release.jks');
const password=process.env.WENJIAN_ANDROID_PASSWORD_FILE||path.join(signing,'store-password.txt');
const alias=process.env.WENJIAN_ANDROID_KEY_ALIAS||'wenjian-reader';
const metadata=JSON.parse(fs.readFileSync(path.join(root,'android/app/build/outputs/apk/release/output-metadata.json'),'utf8'));
const source=path.join(root,'android/app/build/outputs/apk/release',metadata.elements[0].outputFile);
for(const file of [source,keystore,password])if(!fs.existsSync(file))throw Error('缺少构建或签名文件：'+file);
const destination=path.join(root,'outputs/android-release');fs.mkdirSync(destination,{recursive:true});
const apk=path.join(destination,`Wenjian-${metadata.elements[0].versionName}-Android.apk`),aligned=path.join(root,'work/android-tools/aligned-release.apk');
const env={...process.env,JAVA_HOME:javaHome,PATH:path.join(javaHome,'bin')+path.delimiter+process.env.PATH};
const run=(binary,args)=>execFileSync(path.join(sdk,'build-tools/36.0.0',binary),args,{env,encoding:'utf8'});
run('zipalign',['-f','-P','16','4',source,aligned]);
run('apksigner',['sign','--ks',keystore,'--ks-key-alias',alias,'--ks-pass','file:'+password,'--out',apk,aligned]);
const certificate=run('apksigner',['verify','--verbose','--print-certs',apk]);
run('zipalign',['-c','-P','16','4',apk]);
const badging=run('aapt',['dump','badging',apk]);
if(!badging.includes("package: name='com.wenjian.reader'")||badging.includes('application-debuggable'))throw Error('安装包身份或发布模式不正确');
const files=execFileSync('/usr/bin/unzip',['-Z1',apk],{encoding:'utf8'}).trim().split('\n');
const unexpected=files.filter(name=>/\.(pdf|epub|jks|keystore|wenjian-backup)$/i.test(name)||/(reader-store|oss-secure|sync-connection-secure|store-password|notebook\.json)/i.test(name));
if(unexpected.length)throw Error('安装包含不应发布的资料：'+unexpected.join(', '));
for(const asset of ['assets/public/reader/pdf/pdf.worker.min.mjs','assets/public/reader/ocr/chi_sim.traineddata','assets/public/reader/ocr/eng.traineddata','assets/public/unsupported-webview.html'])if(!files.includes(asset))throw Error('缺少离线资源：'+asset);
const sha256=crypto.createHash('sha256').update(fs.readFileSync(apk)).digest('hex');
fs.writeFileSync(path.join(destination,'SHA256SUMS.txt'),sha256+'  '+path.basename(apk)+'\n');
fs.writeFileSync(path.join(destination,'apk-verification.txt'),certificate+'\n'+badging+'\nNo personal books, notebook databases, cloud credentials or signing keys included.\n');
console.log(JSON.stringify({apk,size:fs.statSync(apk).size,sha256,release:true,assetsVerified:true},null,2));
